app_navidad/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

from usuarios.views import UsuarioViewSet, PermissionViewSet, GroupViewSet, ContentTypeViewSet
from documentos_identificaciones.views import DocumentoIdentificacionViewSet
router = routers.DefaultRouter()
router.register(r'usuarios', UsuarioViewSet)
router.register(r'permissions', PermissionViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'content_type', ContentTypeViewSet)
router.register(r'documentos_identificaciones', DocumentoIdentificacionViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',                           include('catalogos_modulos_menus_sub_menus.urls', namespace='catalogo_modulo_menu_sub_menu')),
    url(r'^', 	                        include('usuarios.urls', namespace='usuario')),
    url(r'^', 	                        include('empleados.urls', namespace='empleado')),
    url(r'^empadronamiento-municipal/', 	                        include('empadronados.urls', namespace='empadronado')),
    #REST
    url(r'^api/', 						include(router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogos_modulos_menus_sub_menus/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^modulos/$', views.CatalagoModuloMenuTemplateView.as_view(), name='main'),
    url(r'^empadronamiento-municipal/$', views.EmpadronamientoMunicipalTemplateView.as_view(), name='empadronamiento_municipal'),
    url(r'^empadronamiento-municipal/menu/$', views.EmpadronamientoMunicipalMenuTemplateView.as_view(), name='empadronamiento_municipal_menu'),
]

empleados/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^empleado/nuevo/$', views.EmpleadoCreateView.as_view(), name='create'),
    #url(r'^empleado/(?P<slug>[-\w\W\d]+)/modificar/$', views.EmpleadoUpdateView.as_view(), name='update'),
    url(r'^empleado/(?P<slug>[-\w\W\d]+)/modificar/$', views.EmpleadoUpdate.as_view(), name='update'),
    url(r'^empleado/(?P<slug>[-\w\W\d]+)/$', views.EmpleadoDetailView.as_view(), name='detail'),
    url(r'^empleados/$', views.EmpleadoControlListView.as_view(), name='control'),
    url(r'^empleados/(?P<search_registro>[-\w\W\d]+)/$', views.EmpleadoControlListView.as_view(), name='control'),
]

usuarios/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url, include
from . import views
from django.contrib.auth.views import password_reset
from django.contrib.auth.views import password_reset_confirm
from django.contrib.auth.views import password_reset_complete
from django.contrib.auth.views import password_reset_done
from django.contrib.auth.views import password_change
from django.contrib.auth.views import password_change_done
from django.core.urlresolvers  import reverse_lazy


urlpatterns = [
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^usuario/(?P<slug>[-\w\W\d]+)/cambiar-contraseña/$', views.usuario_password_change, name='password_change'),
    #url(r'^control-de-asistencia/usuario/(?P<slug>[-\w\W\d]+)/cambiar-contraseña/done/$', views.usuario_password_change_done, name='password_change_done'),

    url(r'^restablecer-contraseña/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
            views.usuario_password_reset_confirm, name='password_reset_confirm'),
    url(r'^restablecer-contraseña/$', views.usuario_password_reset, name='password_reset'),
]

index/templates/base_control_panel.html
{% extends 'base_main_modulo_nav.html '%}
{% load widget_tweaks %}
{% load static from staticfiles %}

{% block section %}
<!-- Empleado Nuevo -->
<article class="container">
	<!-- Container Form -->
	<div class="flex-full-center">
			<!-- Formulario -->
			<form action="" method="post" class="form-panel position-relative " enctype="multipart/form-data" id="form">
				{% csrf_token %}
				<div class="container-panel">
					<!-- Panel Head -->
					<div class="panel-head" id="panel_head">
						<!-- Titulo -->
						<div class="border-bottom-red-2">
							<h3 class="rotulo upper-case text-center padding-normal-up-down text-shadow-black color-white">
								Datos Generales
							</h3>
						</div>
						<!-- Menu -->
						<ul class="panel-menu background-red" id="panel_menu">
							{% block panel_menu_item %}
							<li class="background-white">
								<a href="" class="link color-black">
									Menu
								</a>
							</li>
							{% endblock panel_menu_item %}
						</ul>
					</div>
					<!-- Panel Body -->
					<div class="panel-body">
						<div class="panel-left">
							{% block panel_left%}

							{% endblock panel_left%}
						</div>
						<!-- Panel - Right -->
						<div class="panel-right">
							<!-- Datos Personales -->
							<div class="paneles">

								{% block panel_right_componentes %}

								{% endblock panel_right_componentes %}
							</div>
						</div>
					</div>
				</div>

				<div class="container-submit {% block background_panel_submit %} background-gris {% endblock background_panel_submit %}">
					<input type="submit" class="submit" value="Guardar.">
				</div>
				<!-- Mensaje Errores -->
				<div class="mensajeError">
					<p class="textError color-azul font-size-text">
						{% if form.non_field_errors %}
							  {% for err in form.non_field_errors %}
							 	 {{ err }}
							  {% endfor %}
						{% endif %}
					</p>
				</div>
			</form>
		</div>
	</article>

{% endblock section%}

index/templates/base_detail.html
{% extends 'base_main_modulo_nav.html '%}
{% load static from staticfiles %}


{% block section %}
  <article class="container-detalle padding-full">
    <div class="detalle-head border-bottom-red-2 ">
      <h3 class="rotulo padding-normal-up-down upper-case color-white text-shadow-black">
        Perfil del {% block titulo_perfil %} Empleado {% endblock titulo_perfil %}
      </h3>
      <p class="sub-rayado background-red">

      </p>
    </div>
    <div class="detalle padding-normal-up-down ">
        <!-- Datos Perfil -->
      <div class="detalle-left padding-full">
          {% block detalle_left_container %}

          {% endblock detalle_left_container %}
      </div>
      <!-- Datos Personales-->
      <div class="detalle-right">
        {% block detalle_right_container %}
          <div class="border-bottom-red-1">
    				<h3 class="rotulo upper-case color-white text-shadow-black padding-normal-up-down">
    				  Datos Personales
    				</h3>
    			</div>
        {% endblock detalle_right_container %}
      </div>
    </div>

  </article>
{% endblock section %}

index/templates/base_main.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="es">
	<!-- Juegos de Carácteres -->
		<meta charset="utf-8"/>
		<!-- Autor -->
		<meta name="author" content="Carbonell Saravia, Roberto Gian Franco"/>
		<!-- Descripción de la Página Web -->
		<meta name="description" content=" App - ERP"/>
		<!-- Mobile -> verificar si deseas zoom en user-->
		<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"/>
		<!-- Compatibilidad Internet Explorer -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

		<meta name='csrf-token' content={{ csrf_token }}>
		<!-- Titulo -->
		<title>.::{% block title %} {% endblock title %}::.</title>

		<!-- Icono del navegador -->
		<link rel= "shortcut icon" href="{% static "imagenes/png/Escudo_San_Andres.png" %}" type="image/x-icon"/>
		<!-- Estilos y Diseños -->
		<link rel="stylesheet" href="{% static "stylesheet/styles.css" %}"/>


	<body>
		<header class=" {% block position_absolute_header %} {% endblock position_absolute_header %} ">
			{% block header %}
			{% endblock header %}
		</header>
		<nav>
			{% block nav %}
			{% endblock nav %}
		</nav>
		<aside>
			{% block aside %}
			{% endblock aside %}
		</aside>
		<section>
			{% block section %}
			{% endblock section %}
			{% block content %}
			{% endblock content %}
		</section>

		<footer class="{% block position_absolute_footer %} {% endblock position_absolute_footer %}">
			{% block footer %}
			{% endblock footer %}
		</footer>

		{% block script_template %}
		{% endblock script_template %}

		{% block script_config_template %}
		{% endblock script_config_template %}

		{% block plugin %}
		{% endblock plugin %}

	</header>
		<script type="text/javascript" src="{% static "javascript/main.js"%} "></script>

	</body>
</html>

index/templates/base_main_modulo.html
{% extends 'base_main.html '%}
{% load static from staticfiles %}

{% block header %}
	<div class="header-modulo {% block header-modulo-background %} background-black-transparent {% endblock header-modulo-background %}">
		<!-- Avatar - System -->
		<figure class="header-modulo-system">
			<img 
			src="{% block src_avatar_system %} {% static "imagenes/ico/System_1.ico"%} {% endblock src_avatar_system %}" 
			alt="{% block alt_avatar_system %} Sistema E.R.P. Municipal {% endblock alt_avatar_system %}">
		</figure>
		<!-- Nombre - Sistema -->
		<div class="header-modulo-entidad">
			<h2 class="titulo text-center color-white text-shadow-black">
				<a href="{% url 'catalogo_modulo_menu_sub_menu:main' %}" class="link"> Sistema E.R.P. Municipal </a>
			</h2>
		</div>
		<!-- Avatar - Módulo -->
		<figure class="header-modulo-system">
			<img 
			src="{% block src_avatar_modulo %} {% static "imagenes/ico/System_Security_2.ico"%} {% endblock src_avatar_modulo %}" 
			alt="{% block alt_avatar_modulo %} Login {% endblock alt_avatar_modulo %}">
		</figure>
	</div>
{% endblock header %}


{% block footer %}
	<div class="footer-modulo {% block footer-modulo-background %} background-black-transparent {% endblock footer-modulo-background %}">
		<figure class="footer-modulo-logotipo">
			<img src="{% static "imagenes/png/Escudo_San_Andres.png" %}" alt=""/>
			<figcaption class="footer-modulo-logotipo-siglas color-red font-weight-bolder">
				M.D.S.A.
			</figcaption>
		</figure>

		<div class="footer-modulo-web margin-auto-left-right">
			<a class="rotulo link color-white text-center text-shadow-black font-weight-bolder">
				Municipalidad Distrital de San Andrés
			</a>
		</div>

		<figure class="footer-modulo-logotipo" id="creador">
			<figcaption class="footer-modulo-logotipo-siglas color-red font-weight-bolder">
				S.G.T.I.
			</figcaption>
			<img class="radius-circular" src="{% static "imagenes/jpg/Ojo_Bionico_1.jpg" %}" alt=""/>
		</figure>
	</div>
{% endblock footer %}

index/templates/base_main_modulo_menu.html
{% extends 'base_main_modulo_nav.html'%}
{% load static from staticfiles %}
{% block aside %}
	<div class="aside-modulo" id="aside_menu_modulo">
		<!-- Head -->
		<div class="aside-modulo-head border-bottom-white-1 {% block background_head_menu %} background-verde-pastel {% endblock background_head_menu %}">
			<p class="color-white font-size-text-1-5 text-center text-shadow-black font-weight-bolder">
				Menu - Módulo
			</p>
			<div id="boton_close_menu_container">
				
			</div>
		</div>
		<!-- Menu -->
		<ul class="aside-modulo-items">
			{%for catalogo_modulo in catalogos_modulos%} 
			<!-- Menu - Item -->
			<li class="aside-modulo-items-item">
				<!-- Menu - Item - Container -->
				<figure class="aside-modulo-items-item-container">
					<!-- Menu - Item - Container - Imagen -->
					<a href="{{catalogo_modulo.url}}">
						<img 
						src="{{catalogo_modulo.imagen.url}}"
						alt="{{catalogo_modulo.modulo}}">
					</a>
					<!-- Menu - Item - Container - Nombre -->
					<figcaption  
					class="{% block background_nombre_modulo %} background-verde-pastel {% endblock background_nombre_modulo %}
					border-white-1 border-radius-medium box-shadow-black-transparent">
						<!-- Menu - Item - Container -Imagen - Link -->
						<a href="{{catalogo_modulo.url}}" class="link text-shadow-black font-weight-bolder ">
							{{catalogo_modulo.modulo}}
						</a>
					</figcaption>
				</figure>
			</li>
			{% endfor %} 
		</ul>
	</div>
{% endblock aside %}

{% block section %}
	<!-- Saludo -->
	<div class="container">
		<p class="titulo padding-full color-white text-shadow-black font-weight-bolder">
			Bienvenidos
		</p>
		<p class="sub-rayado background-red">
			
		</p>
	</div>
	<div class="section-modulo">
		<!-- Menu -->
		<ul class="menu">
			 {%for catalogo_modulo_menu in catalogos_modulos_menus%} 
			<!-- Menu - Item -->
			<li class="menu-item">
				<!-- Menu - Item - Container -->
				<figure class="menu-item-container ">
					<!-- Menu - Item - Container - Imagen -->
					<img 
					src="{% block imagen_src %} {{catalogo_modulo_menu.imagen.url}} {% endblock imagen_src %}" 
					alt="{% block imagen_alt %} {{catalogo_modulo_menu.modulo}} {% endblock imagen_alt %}" 
					class="menu-item-container-imagen">
					<!-- Menu - Item - Container - Nombre -->
					<figcaption  class="menu-item-container-nombre border-white-1 border-radius-medium box-shadow-black-transparent 
					{% block background_nombre_item %} background-verde-pastel {% endblock background_nombre_item %}">
						<!-- Menu - Item - Container -Imagen - Link -->
						<a href="{{catalogo_modulo_menu.url}}" class="link text-shadow-black font-weight-bolder ">
							{% block nombre_item %} {{catalogo_modulo_menu.menu}} {% endblock nombre_item %}
						</a>
					</figcaption>
				</figure>
			</li>
			{% endfor %} 
		</ul>
	</div>
{% endblock section %}

index/templates/base_main_modulo_menu_control.html
{% extends 'base_main_modulo_nav.html'%}
{% load static from staticfiles %}

{% block section %}
	<!-- Panel de Control -->
	<article class="control">
		<!-- Control - Head -->
		<div class="control-head">
			<!-- Titulo -->
			<div class="control-head-titulo ">
				<h3 class="subtitulo upper-case color-white text-shadow-black text-center">
					Panel de {% block panel_nombre_menu %} Menu {% endblock panel_nombre_menu%}
				</h3>
			</div>

		</div>
		<!-- Control - Body -->
		<div class="control-body">
			<!-- Acciones -->
			<div class="actions">
				<!-- Search -->
				<div class="search" id="container_form_search_registro">
					<form action="{% block action_form_search_ %} {% endblock action_form_search_ %}" method="GET" class="form-search" id="form_search_input">

						<!-- Icono -->
						<div class="icono">
							<!-- Label - Search -->
							<label for="input_search_registro" class="icono-label font-size-text-1-5  icon-search">

							</label>
						</div>
						<!-- Input - Search -->
						<div class="container" id="container_search_registro">
							<!-- Template - Input -->

						</div>
					</form>
				</div>
				<!-- Agregar Registro Nuevo -->
				<div class="add">
			   		<!-- Botón Agregar - Movil -->
   						<div class="container-boton-small
   						{% block background_agregar_movil %} background-gray {% endblock background_agregar_movil %}
   						radius-circular box-shadow-black border-white-2" id="boton_agregar_movil">
   					    	<a href="{% block url_agregar_registro_movil %} {% endblock url_agregar_registro_movil %}" class="boton-small ">
   					    		+
   					    	</a>
   				   		</div>
   				   		<!-- Botón Agregar - Desktop -->
   				   		<div class="container-boton
   				   		{% block background_agregar_desktop %} background-gray {% endblock background_agregar_desktop %}
   				   		box-shadow-black-transparent font-weight-bolder " id="boton_agregar_desktop">
   					    	<a href="{% block url_agregar_registro_desktop %} {% endblock url_agregar_registro_desktop %}" class="container-boton-link">
   					    		Nuevo Registro.
   					    	</a>
   				   		</div>
				</div>
			</div>
			<!-- Table - Container -->
			<div class="container-table background-white" id="table_usuario">
				<!-- Table -->
				<table class="table" class="table">
					<!-- Table - Head -->
					<thead class="table-head {% block background_table_head %} background-gray {% endblock background_table_head %}">
						<tr class="table-head-row upper-case">
							{% block table_column %}
							<th class="table-head-row-column"><a href="" class="link"> Columna </a></th>
							{% endblock table_column %}
						</tr>
					</thead>
					<!-- Table - Body -->
					<tbody class="table-body" id="container_table_body">
						{% block table_row %}
							{% if object_list.count > 0 %}
								{% include "usuario_table.html" %}
							{% else %}
								{% include "usuario_table.html" %}
							{% endif %}
						{% endblock table_row %}
					</tbody>
				</table>
			</div>
			<!-- Paginación -->
			<div class="paginacion">
				<!-- Paginas -->
			    <div class="paginas border-white-1 {% block background_paginas %} background-gray {% endblock background_paginas %} ">
	    		    <!-- Botón Atras - Prev -->
	    	    	{% if page_obj.has_previous %}
	    	    		<!-- Pagina - Prev - No Select -->
	    		        <div class="paginas-prev">
	    		       		<a href="?{{ page_obj.previous_page_number.querystring }}" class="paginas-prev-noselect icon-chevron-left {% block boton_pagina_prev_color %} {% endblock boton_pagina_prev_color %}"> </a>
	    		        </div>
	    	    	{% else %}
	    	    	   <!-- Pagina - Prev - Select -->
	    		        <div class="paginas-prev">
	    		       		<span class="paginas-prev-select icon-chevron-left"> </span>
	    		        </div>
	    	    	{% endif %}

	    		    <!-- Rango de Páginas -->
	    			<div class="paginas-rango">
	    			    {% for page in page_obj.pages %}
	    			        {% if page %}
	    			            {% ifequal page page_obj.number %}
	    			           		<!-- Pagina No Select -->
	    			                <div class="pagina">
	    			               		<span class="pagina-select {% block fondo_border %} background-white {% endblock fondo_border %}">{{ page }}</span>
	    			               	</div>
	    			            {% else %}
	    			            	<!-- Pagina Select -->
	    			                <div class="pagina">
	    			                	<a href="?{{ page.querystring }}" class="pagina-noselect">{{ page }}</a>
	    			                </div>
	    			            {% endifequal %}
	    			        {% else %}
	    			        	  <!-- Pagina - Varios -->
	    			            <div class="pagina">
	    			            	<span class="pagina-varios">
	    			            		...
	    			            	</span>
	    			            </div>
	    			        {% endif %}
	    			    {% endfor %}
	    		    </div>
	    		    <!-- Botón Adelante - Next -->
	    		    {% if page_obj.has_next %}
	    		  	    <!-- Pagina - Next - No Select -->
	    		        <div class="paginas-next">
	    		        	<a href="?{{ page_obj.next_page_number.querystring }}"
	    		        	class="paginas-next-noselect icon-chevron-right
	    		        	{% block boton_pagina_next_color %} {% endblock boton_pagina_next_color%} "> </a>
	    		        </div>
	    		    {% else %}
	    		    	<!-- Pagina - Next - Select -->
	    		        <div class="paginas-next">
	    		        	<span class="paginas-next-select icon-chevron-right"> </span>
	    		        </div>
	    		    {% endif %}
			    </div>
			</div>
			<!-- Detalles -->
			<div class="detalles">
				<!-- Total de Registro -->
				<div class="total font-weight-bolder color-red">
					<p class="total-items">
						<!-- Valor Total -->
						Total: <span class="total-valor color-black">
								{% if total_registro == 0 %}
									0
								{% else %}
									{{total_registro}}
								{% endif %}
							   </span>
					</p>
					<!-- Botón Eliminar - Movil -->
					<div class="container-boton-small
					 {% block background_eliminar_movil %} background-gray {% endblock background_eliminar_movil %}
					 radius-circular box-shadow-black border-white-2" id="boton_eliminar_movil">
				    	<a href="" class="boton-small ">
				    		X
				    	</a>
			   	</div>
			   		<!-- Botón Eliminar - Desktop -->
			   	<div class="container-boton
			   			{% block background_eliminar_desktop %} background-gray {% endblock background_eliminar_desktop %}
			   			box-shadow-black-transparent" id="boton_eliminar_desktop">
				    	<a href="" class="container-boton-link">
				    		Eliminar Registro(s)
				    	</a>
			   	</div>
				</div>
				<!-- Buscar - Página -->
				<div class="search-pagina padding-normal-up-down ">
					<!-- Form - Search -->
					<form action="" method="get" class="form-pagina">
						<!-- Label - Search -->
						<label for="search_numero_pagina" class="font-weight-bolder">N° Página</label>
						<!-- Input - Search -->
						<input type="number" name="page" min="1" class="number input-field-default" id="search_numero_pagina">
						<!-- Submit - Go -->
						<div class="container-submit-small
						{% block background_search_pagina_submit %} background-gray {% endblock background_search_pagina_submit %}
						border-white-2 box-shadow-black-transparent">
							<input type="submit" class="submit" value="ir">
						</div>
					</form>
				</div>
			</div>
		</div>
	</article>
{% endblock section %}

index/templates/base_main_modulo_menu_descripcion.html
{% extends 'base_main_modulo_nav.html'%}
{% load static from staticfiles %}
{% block section %}
	<!-- Módulo -->
	<div class="modulo">
		<!-- Módulo Main -->
		<div class="modulo-main">
			<!-- Módulo - Avatar -->
			<figure class="modulo-main-avatar">
				<!-- Módulo - Avatar - Imagen -->
				<img
				src="{% block src_modulo_avatar_input %} {% static "imagenes/ico/System_1.ico"%} {% endblock src_modulo_avatar_input %}"
				alt="{% block alt_modulo_avatar_input %} {% static "imagenes/ico/System_1.ico"%} {% endblock alt_modulo_avatar_input %}"
				class="modulo-main-avatar-imagen">
				<!-- Módulo - Avatar - Nombre -->
				<figcaption class="modulo-main-avatar-nombre {% block nombre_modulo_styles_class %} border-bottom-gray-1 {% endblock nombre_modulo_styles_class %}">
					{% block nombre_modulo %} Nombre Módulo {% endblock nombre_modulo %}
				</figcaption>
			</figure>
			<!-- Boton Ingresar -->
			<div class="modulo-main-boton">
				<div class="{% block background_boton_ingresar %} background-black-transparent {% endblock background_boton_ingresar %}">
					<a href="{% block url_modulo_menu %} {% endblock url_modulo_menu%}" class="link border-white-1"> Ingresar </a>
				</div>
			</div>
			<!-- Nota Privilegios -->
			<div class="auth">
				<p class="color-red text-center">
					Solo los usuarios con privilegios autorizados tienen acceso a este módulo del sistema.
				</p>
			</div>
		</div>

		<!-- Módulo - Detalles -->
		<div class="modulo-detail">
			<!--  Módulo - Descripción -->
			<div class="modulo-detail-descripcion {% block descripcion_border_bottom %} border-bottom-gray-2 {% endblock descripcion_border_bottom %}">
				<p class="color-white text-shadow-black font-weight-bolder ">
					Descripción
				</p>
				<div class="modulo-detail-descripcion-contenido box-shadow-black-transparent ">
					<p>
						{% block modulo_descripcion %}
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim non rerum voluptates voluptatem aspernatur cumque quaerat sed impedit dolore natus quis officia harum, eum repellendus neque fuga reprehenderit magni, id.
						{% endblock modulo_descripcion %}
					</p>
				</div>
			</div>
			<!--  Módulo - Observación -->
			<div class="modulo-detail-observacion {% block observacion_border_bottom %} border-bottom-gray-2 {% endblock observacion_border_bottom %}">
				<p class="color-white text-shadow-black font-weight-bolder ">
					Observación
				</p>
				<div class="modulo-detail-observacion-contenido box-shadow-black-transparent ">
					<p>
						{% block modulo_observacion %}
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim non rerum voluptates voluptatem aspernatur cumque quaerat sed impedit dolore natus quis officia harum, eum repellendus neque fuga reprehenderit magni, id.
						{% endblock modulo_observacion %}
					</p>
				</div>
			</div>

		</div>
	</div>
{% endblock section %}

index/templates/base_main_modulo_nav.html
{% extends 'base_main_modulo.html '%}
{% load static from staticfiles %}
{% block nav %}
	<div class="nav-modulo {% block nav-border %} border-bottom-gray-1 {% endblock nav-border %}">
		<!-- Módulo Head -->
		<div class="nav-modulo-head">

			<!-- Usuario -->
			<div class="usuario">
				{% if boton_menu == True %}
					<div>
						<a href="{% block url_menu_control %} {% endblock url_menu_control %}" class="color-black">Panel Menu</a>
					</div>
				{% elif boton_menu == False %}
				  <div>

				  </div>
				{% elif boton_menu == None %}
					<div class="usuario-boton" id="boton_open_menu_container">

					</div>
				{% endif%}
				<!-- Usuario - Container -->
				<figure class="usuario-datos">
					<!-- Usuario - Nombre -->
					<figcaption class="usuario-datos-nombre">
						<p class="color-white text-shadow-black font-weight-bolder">
							@{{instance.usuario.username}}
						</p>
					</figcaption>
					<!-- Usuario - Imagen -->
					<img src="{{instance.fotografia.url}}" alt="{{instance.usuario.username}}" class="usuario-datos-avatar box-shadow-black-transparent radius-circular">
					<!-- Usuario - Botón -->
					<div class="usuario-datos-boton " id="boton_usuario_dato_container">

					</div>
				</figure>
				<!-- Configuración Usuario -->
				<ul id="usuario_panel_configuracion"class="usuario-configuracion border-white-2 box-shadow-black background-gray font-weight-bolder">
					<!-- Configuración Usuario - Perfil Usuario -->
					{% if instance %}
						{% if "Empleado" == instance.tipo_perfil %}
							<li>
								<a href="{% url "empleado:detail" instance.slug %}" class="link text-shadow-black text-center text-shadow-black">
									 Perfil de {{instance.tipo_perfil}}
								</a>
							</li>
						{% endif %}
					{% else %}
						<li>
							<a href="#" class="link text-shadow-black text-center text-shadow-black">
								 Sin Perfil
							</a>
						</li>
					{% endif %}
					<!-- Configuración Usuario - Salir -->
					<li>
						<a href="{% url 'usuario:logout' %}" class="link text-shadow-black text-center text-shadow-black"> Salir </a>
					</li>
				</ul>
			</div>

		</div>
	</div>

{% endblock nav %}

{% block script_config_template %}
	<script id ="boton_usuario_dato_template" type="text/template">
		<a href="" id="boton_usuario_dato" class="icon-settings2 font-size-text-1-5  text-shadow-black font-weight-bolder">

		</a>
	</script>
	<script id ="boton_close_menu_template" type="text/template">
		<a href="" id="boton_close_menu" class="usuario-boton-link icon-grid font-size-text-1-5  text-shadow-black font-weight-bolder">

		</a>
	</script>
	<script id ="boton_open_menu_template" type="text/template">
		<a href="" id="boton_open_menu" class="usuario-boton-link icon-grid font-size-text-1-5  text-shadow-black font-weight-bolder">

		</a>
	</script>
{% endblock script_config_template %}