app_navidad/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

from usuarios.views import UsuarioViewSet, PermissionViewSet, GroupViewSet, ContentTypeViewSet
from documentos_identificaciones.views import DocumentoIdentificacionViewSet
router = routers.DefaultRouter()
router.register(r'usuarios', UsuarioViewSet)
router.register(r'permissions', PermissionViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'content_type', ContentTypeViewSet)
router.register(r'documentos_identificaciones', DocumentoIdentificacionViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',                           include('catalogos_modulos_menus_sub_menus.urls', namespace='catalogo_modulo_menu_sub_menu')),
    url(r'^', 	                        include('usuarios.urls', namespace='usuario')),
    url(r'^', 	                        include('empleados.urls', namespace='empleado')),
    url(r'^empadronamiento-municipal/', 	                        include('empadronados.urls', namespace='empadronado')),
    #REST
    url(r'^api/', 						include(router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleados/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^empleado/nuevo/$', views.EmpleadoCreateView.as_view(), name='create'),
    #url(r'^empleado/(?P<slug>[-\w\W\d]+)/modificar/$', views.EmpleadoUpdateView.as_view(), name='update'),
    url(r'^empleado/(?P<slug>[-\w\W\d]+)/modificar/$', views.EmpleadoUpdate.as_view(), name='update'),
    url(r'^empleado/(?P<slug>[-\w\W\d]+)/$', views.EmpleadoDetailView.as_view(), name='detail'),
    url(r'^empleados/$', views.EmpleadoControlListView.as_view(), name='control'),
    url(r'^empleados/(?P<search_registro>[-\w\W\d]+)/$', views.EmpleadoControlListView.as_view(), name='control'),
]

usuarios/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url, include
from . import views
from django.contrib.auth.views import password_reset
from django.contrib.auth.views import password_reset_confirm
from django.contrib.auth.views import password_reset_complete
from django.contrib.auth.views import password_reset_done
from django.contrib.auth.views import password_change
from django.contrib.auth.views import password_change_done
from django.core.urlresolvers  import reverse_lazy


urlpatterns = [
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^usuario/(?P<slug>[-\w\W\d]+)/cambiar-contraseña/$', views.usuario_password_change, name='password_change'),
    #url(r'^control-de-asistencia/usuario/(?P<slug>[-\w\W\d]+)/cambiar-contraseña/done/$', views.usuario_password_change_done, name='password_change_done'),

    url(r'^restablecer-contraseña/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
            views.usuario_password_reset_confirm, name='password_reset_confirm'),
    url(r'^restablecer-contraseña/$', views.usuario_password_reset, name='password_reset'),
]

empleados/models.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

from infos_sistemas.models import InfoSistema
from django.template.defaultfilters import slugify

from personas.models import Persona
from cargos.models import Cargo
from grados_instrucciones.models import GradoInstruccion
from tipos_empleados.models import TipoEmpleado
from profesiones.models import Profesion
from ocupaciones.models import Ocupacion
from usuarios.models import Usuario
from areas.models import Area


class Empleado(Persona):
	BOOL_ACTIVO 		 			= ((True, 'Si'), (False, 'No'))
	area							= models.ForeignKey(Area)
	usuario							= models.OneToOneField(Usuario, unique=True, related_name='usuario_empleados_related')
	tipo_empleado    				= models.ForeignKey(TipoEmpleado)
	cargo 	  				    	= models.ForeignKey(Cargo)
	grado_instruccion 				= models.ForeignKey(GradoInstruccion, verbose_name='Grado instrucción')
	profesion 		  				= models.ForeignKey(Profesion, verbose_name='Profesión')
	ocupacion 		  				= models.ForeignKey(Ocupacion, blank=True, null=True, default=None, verbose_name='Ocupación')
	fecha_inicio_contratacion 		= models.DateField(verbose_name='Fecha inicio contratación', help_text="Seleccionar fecha de inicio de contratación del empleado.")
	fecha_fin_contratacion 			= models.DateField(verbose_name='Fecha fin contratación', blank=True, null=True, help_text="Seleccionar fecha de final de contratación del empleado.")
	fecha_cese						= models.DateTimeField(blank=True, null=True, help_text="Seleccionar fecha de cese del empleado.")
	descripcion_empleado		    = models.TextField(verbose_name='Descripción (Empleado)' ,blank=True, null=True, help_text='(Opcional).')
	observacion_empleado		   	= models.TextField(verbose_name='Observación (Empleado)' ,blank=True, null=True, help_text='(Opcional).')
	activo 							= models.BooleanField(choices=BOOL_ACTIVO, default=True)

		#Métodos
	#Python 3.X
	def __str__(self):
		return self.get_nombre_completo()

	#Python 2.X
	#def __unicode__(self):
	#	return self.nombre

	def save(self, *args, **kwargs):
		if not self.pk:
			self.slug = slugify(self.get_nombre_completo())
		else:
			slug = slugify(self.get_nombre_completo())
			if self.slug != slug:
				self.slug = slug
		super(Empleado, self).save(*args, **kwargs)

	#Opciones
	class Meta:
		#Nombre para la tabla del gestor de base de datos
		db_table = 'Empleados'
		#Ordenar los registros por un campo especifico
		ordering = ('apellido_paterno',)
		#Nombre para el Conjunto de Objetos en el Panel de Administración
		verbose_name = 'Empleado'
		#Nombre en Plural en la lista de módulos en el Panel de Administración
		verbose_name_plural = 'Empleados'#Métodos

empleados/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from .models import Empleado
from django.contrib.admin import widgets
from betterforms.multiform import MultiModelForm
from usuarios.forms import UsuarioModelForm


class EmpleadoModelForm(forms.ModelForm):
	class Meta:
		model  = Empleado
		exclude = ['tipo_persona',  'usuario',
				  'slug', 'fecha_registro', 'usuario_creador', 'nombre_host', 'direccion_ip',
				  'fecha_ultima_actualizacion', 'ultimo_usuario_editor', 'ultimo_nombre_host', 'ultimo_direccion_ip']

		widgets = {
			'tipo_persona'				   : forms.RadioSelect(attrs={'class':'radio-button-field-default'}),
			'apellido_paterno'			   : forms.TextInput(attrs={'class':'input-field-default'}),
			'apellido_materno'			   : forms.TextInput(attrs={'class':'input-field-default'}),
			'nombre'					   : forms.TextInput(attrs={'class':'input-field-default'}),
			'descripcion_empleado' 		   : forms.Textarea(attrs={'class':'input-field-area-default'}),
			'observacion_empleado' 		   : forms.Textarea(attrs={'class':'input-field-area-default'}),
			'documento_identificacion'	   : forms.Select(attrs={'class':'select-field-default'}),
			'numero_documento_identificacion'	   : forms.TextInput(attrs={'class':'select-field-default'}),
			'fecha_nacimiento'				: forms.DateInput(attrs={'class':'date-field-default'}),
			'genero'						: forms.RadioSelect(attrs={'class':'radio-button-field-default'}),
			'estado_civil'					: forms.Select(attrs={'class':'select-field-default'}),
			'grupo_sanguineo'				: forms.Select(attrs={'class':'select-field-default'}),
			'hijo'							: forms.RadioSelect(attrs={'class':'radio-button-field-default'}),
			'numero_hijo'					: forms.NumberInput(attrs={'class':'input-field-default'}),
			'celular'						: forms.NumberInput(attrs={'class':'input-field-default'}),
			'telefono'						: forms.NumberInput(attrs={'class':'input-field-default'}),
			'email'							: forms.EmailInput(attrs={'class':'input-field-default'}),
			'fotografia'    				    : forms.FileInput(attrs={'class':'input-file'}),
			'observacion_persona' 		    : forms.Textarea(attrs={'class':'input-field-area-default'}),

			'distrito' 		   				: forms.Select(attrs={'class':'select-field-default'}),
			'zona' 		   					: forms.Select(attrs={'class':'select-field-default'}),
			'via' 		   					: forms.Select(attrs={'class':'select-field-default'}),
			'observacion_zona_via'			: forms.Textarea(attrs={'class':'input-field-area-default'}),

			'nombre_zona_via'						 : forms.TextInput(attrs={'class':'input-field-default'}),
			'numero_letra_asociado_nombre_via'		 : forms.TextInput(attrs={'class':'input-field-default'}),
			'prefijo_bis_vial'						 : forms.CheckboxInput(attrs={'class':''}),
			'numero_letra_asociado_prefijo_bis_vial' : forms.TextInput(attrs={'class':'input-field-default'}),
			'cuadrante_vial'						 : forms.Select(attrs={'class':'select-field-default'}),


			'numero_via_generadora' 					 	: forms.NumberInput(attrs={'class':'input-field-default'}),
			'numero_letra_asociado_numero_via_generadora'	: forms.TextInput(attrs={'class':'input-field-default'}),
			'prefijo_bis_numero_via_generadora'				: forms.CheckboxInput(attrs={'class':''}),
			'numero_letra_asociado_prefijo_bis_numero_via_generadora'	: forms.TextInput(attrs={'class':'input-field-default'}),
			'numero_placa'									: forms.NumberInput(attrs={'class':'input-field-default'}),
			'cuadrante_via_generadora' 						: forms.Select(attrs={'class':'select-field-default'}),

			'division_area_urbana'						: forms.Select(attrs={'class':'select-field-default'}),
			'nombre_division_area_urbana'				: forms.TextInput(attrs={'class':'input-field-default'}),

			'nucleo_residencial'						: forms.Select(attrs={'class':'select-field-default'}),
			'nombre_nucleo_residencial'					: forms.NumberInput(attrs={'class':'input-field-default'}),

			'ubicacion_predio'							: forms.Select(attrs={'class':'select-field-default'}),
			'identificador_ubicacion_predio'			: forms.TextInput(attrs={'class':'input-field-default'}),

			'tipo_predio'						: forms.Select(attrs={'class':'select-field-default'}),
			'nombre_tipo_predio'				: forms.NumberInput(attrs={'class':'input-field-default'}),


			'denominacion'					: forms.TextInput(attrs={'class':'input-field-default'}),
			'referencia'					: forms.Textarea(attrs={'class':'input-field-area-default'}),

			'complemento_ubicacion_tipo_predio' 		     : forms.Select(attrs={'class':'select-field-default'}),
			'numero_letra_complemento_ubicacion_tipo_predio' : forms.TextInput(attrs={'class':'input-field-default'}),

			'area'							: forms.Select(attrs={'class':'select-field-default'}),
			'tipo_empleado'					: forms.Select(attrs={'class':'select-field-default'}),
			'cargo'							: forms.Select(attrs={'class':'select-field-default'}),
			'grado_instruccion'				: forms.Select(attrs={'class':'select-field-default'}),
			'profesion'						: forms.Select(attrs={'class':'select-field-default'}),
			'ocupacion'						: forms.Select(attrs={'class':'select-field-default'}),
			'fecha_inicio_contratacion'		: forms.DateInput(attrs={'class':'date-field-default'}),
			'fecha_fin_contratacion'		: forms.DateInput(attrs={'class':'date-field-default'}),
			'fecha_cese'					: forms.DateInput(attrs={'class':'date-field-default'}),
			'activo'						: forms.CheckboxInput(attrs={'class':''}),

	      }


class EmpleadoUsuarioForm(MultiModelForm):
	form_classes = {
        'model_form_empleado': EmpleadoModelForm,
        'model_form_usuario': UsuarioModelForm,
    }

empleados/views.py
# -*- encoding: utf-8 -*-
from django.conf import settings
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from .models import Empleado
from .forms import EmpleadoModelForm, EmpleadoUsuarioForm
from django.core.urlresolvers import reverse_lazy
from rest_framework import viewsets
from django.db.models import Q
import socket
from pure_pagination.mixins import PaginationMixin
from django.template.defaultfilters import slugify

from infos_sistemas.mixins import TipoPerfilUsuarioMixin

class EmpleadoCreateView(TipoPerfilUsuarioMixin, CreateView):
    template_name = 'empleado_create.html'
    form_class    	  = EmpleadoUsuarioForm
    model         = Empleado
    success_url   = reverse_lazy('empleado:control')

    def form_valid(self, form):
        user = form['model_form_usuario'].save(commit=False)
        user.usuario_creador      = self.request.user
        user.ultimo_usuario_editor = user.usuario_creador
        try:
            user.nombre_host = socket.gethostname()
            user.ultimo_nombre_host = user.nombre_host
        except:
           user.nombre_host  = 'localhost'
           user.ultimo_nombre_host = user.nombre_host
        user.direccion_ip    = socket.gethostbyname(socket.gethostname())
        user.ultimo_direccion_ip =  socket.gethostbyname(socket.gethostname())


        empleado = form['model_form_empleado'].save(commit=False)
        empleado.tipo_persona = 'Natural'
        if empleado.numero_hijo is None:
            empleado.numero_hijo = 0

        user.save()

        empleado.usuario = user
        empleado.usuario_creador      = self.request.user
        empleado.ultimo_usuario_editor = empleado.usuario_creador
        try:
            empleado.nombre_host = socket.gethostname()
            empleado.ultimo_nombre_host = empleado.nombre_host
        except:
           empleado.nombre_host  = 'localhost'
           empleado.ultimo_nombre_host = empleado.nombre_host
        empleado.direccion_ip    = socket.gethostbyname(socket.gethostname())
        empleado.ultimo_direccion_ip =  socket.gethostbyname(socket.gethostname())

        empleado.save()

        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdate(TipoPerfilUsuarioMixin, UpdateView):
    form_class      = EmpleadoModelForm
    success_url     = reverse_lazy('empleado:control')
    template_name   = 'empleado_update.html'
    queryset        = Empleado.objects.all()


    def form_valid(self, form):
        self.object = form.save(commit=False)
        if self.object.numero_hijo  is None:
            self.object.numero_hijo = 0
        self.object.ultimo_usuario_editor = self.request.user
        try:
            self.object.ultimo_nombre_host = socket.gethostname()
        except:
           self.object.ultimo_nombre_host  = 'localhost'

        self.object.ultimo_direccion_ip    = socket.gethostbyname(socket.gethostname())
        self.object.save()

        return super(EmpleadoUpdate, self).form_valid(form)

class EmpleadoUsuarioUpdateView(TipoPerfilUsuarioMixin, UpdateView):
    form_class      = EmpleadoUsuarioForm
    success_url     = reverse_lazy('empleado:control')
    template_name   = 'empleado_usuario_update.html'
    queryset        = Empleado.objects.all()

    def get_context_data(self, **kwarg):
        context  = super(EmpleadoUpdateView, self).get_context_data(**kwarg)
        empleado  = self.queryset.get(slug__contains=self.kwargs['slug'])
        data = {'empleado':empleado}
        context.update(data)
        return context

    def get_form_kwargs(self):
        kwargs = super(EmpleadoUpdateView, self).get_form_kwargs()
        kwargs.update(instance={
            'model_form_empleado': self.object,
            'model_form_usuario': self.object.usuario,
        })
        return kwargs

    def form_valid(self, form):
        empleado = self.queryset.get(slug__contains=self.kwargs['slug'])
        user = form['model_form_usuario'].save(commit=False)
        user = empleado.usuario
        user.ultimo_usuario_editor = self.request.user
        try:
            user.ultimo_nombre_host = user.nombre_host
        except:
           user.ultimo_nombre_host = user.nombre_host
        user.ultimo_direccion_ip =  socket.gethostbyname(socket.gethostname())

        empleado = form['model_form_empleado'].save(commit=False)
        empleado.tipo_persona = 'Natural'
        if empleado.numero_hijo is None:
            empleado.numero_hijo = 0
        user.save()

        empleado.usuario = user
        empleado.ultimo_usuario_editor = self.request.user
        try:
            empleado.ultimo_nombre_host = empleado.nombre_host
        except:
           empleado.ultimo_nombre_host = empleado.nombre_host
        empleado.ultimo_direccion_ip =  socket.gethostbyname(socket.gethostname())
        empleado.save()
        return super(EmpleadoUpdateView, self).form_valid(form)


class EmpleadoDetailView(TipoPerfilUsuarioMixin, DetailView):
    template_name   = 'empleado_detail.html'
    model           = Empleado
    queryset        = Empleado.objects.all()


class EmpleadoControlListView(PaginationMixin, TipoPerfilUsuarioMixin, ListView):
    model         = Empleado
    template_name = 'empleados.html'
    paginate_by   = 10

    def get_context_data(self, **kwarg):
        context     = super(EmpleadoControlListView, self).get_context_data(**kwarg)
        boton_menu     = False
        total_registro = self.model.objects.count()

        data = {
            'boton_menu'    : boton_menu,
            'total_registro': total_registro,
        }

        context.update(data)
        return context

    def get(self, request, *args, **kwargs):
        if request.GET.get('search_registro', None):
            self.object_list = self.get_queryset()
            context = self.get_context_data()
            return self.render_to_response(context)
        else:
            return super(EmpleadoControlListView, self).get(self, request, *args, **kwargs)

    def get_queryset(self):
        if self.request.GET.get('search_registro', None):
            value = self.request.GET.get('search_registro', None)
            queryset = self.model.objects.filter(Q(slug__icontains=slugify(value)))
        else:
            queryset = super(EmpleadoControlListView, self).get_queryset()
        return queryset

empleados/templates/empleado_detail.html
{% extends 'base_detail.html '%}

{% block detalle_left_container %}
<figure class="container ">
  <img class="imagen-perfil border-black-2 margin-auto-left-right background-white"
       src="{{object.fotografia.url}}"
       alt="{{object.get_nombre_completo}}"/>
  <figcaption class="detalle-nombre padding-normal-left-right">
    <a href="{% url "empleado:update" object.slug %}" class="rotulo link padding-normal-up-down display-block text-center font-weight-bolder text-shadow-black">
      <p>
        {{object.nombre}}
      </p>
      <p>
        {{object.apellido_paterno}} {{object.apellido_materno}}
      </p>
    </a>
    <p class="text-center border-top-red-1  padding-normal-up-down color-gris-oscuro font-weight-bolder ">
        {{object.cargo}} de {{object.area.nombre}}
    </p>
  </figcaption>

  <div class="group-detalle">
    <div class="detalle-item">
      <p class="detalle-item-label font-weight-bolder">
        Descripción (Empleado)
      <p class="detalle-item-area font-weight-bolder">
        {{object.descripcion_empleado}}
      </p>
    </div>
  </div>

  <div class="group-detalle">
    <div class="detalle-item">
      <p class="detalle-item-label font-weight-bolder">
        Observación (Empleado)
      <p class="detalle-item-area font-weight-bolder">
        {{object.observacion_empleado}}
      </p>
    </div>
  </div>
</figure>
{% endblock detalle_left_container %}
{% block detalle_right_container %}
<div class="group-detalle">
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
        Documento identificación
    <p class="detalle-item-value font-weight-bolder">
      {{object.documento_identificacion}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
        Número documento identificación
    <p class="detalle-item-value font-weight-bolder">
      {{object.numero_documento_identificacion}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Fecha de nacimiento
    <p class="detalle-item-value font-weight-bolder">
      {{object.fecha_nacimiento}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Género
    <p class="detalle-item-value font-weight-bolder">
      {{object.genero}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Estado civil
    <p class="detalle-item-value font-weight-bolder">
      {{object.estado_civil}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Grupo sanguíneo
    <p class="detalle-item-value font-weight-bolder">
      {{object.grupo_sanguineo}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Hijo(s)
    <p class="detalle-item-value font-weight-bolder">
      {% if object.hijo == True %}
        Si
      {% else %}
        No
      {% endif %}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Número hijo(s)
    <p class="detalle-item-value font-weight-bolder">
      {{object.numero_hijo}}
    </p>
  </div>
</div>
<!-- Datos Empleados -->
<div class="border-bottom-red-1">
  <h3 class="rotulo upper-case color-white text-shadow-black padding-normal-up-down">
    Datos Empleados
  </h3>
</div>
<div class="group-detalle">
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
        Área | Dependencia
    <p class="detalle-item-value font-weight-bolder">
      {{object.area}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
        Tipo empleado
    <p class="detalle-item-value font-weight-bolder">
      {{object.tipo_empleado}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
        Grado instrucción
    <p class="detalle-item-value font-weight-bolder">
      {{object.grado_instruccion}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Profesión
    <p class="detalle-item-value font-weight-bolder">
      {{object.profesion}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Ocupación
    <p class="detalle-item-value font-weight-bolder">
      {{object.ocupacion}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Fecha inicio contratación
    <p class="detalle-item-value font-weight-bolder">
      {{object.fecha_inicio_contratacion}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Fecha fin contratacion
    <p class="detalle-item-value font-weight-bolder">
      {% if object.fecha_fin_contratacion %}
        {{object.fecha_fin_contratacion}}
      {% else %}
        -------
      {% endif %}
    </p>
  </div>

  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Fecha cese
    <p class="detalle-item-value font-weight-bolder">
      {% if object.fecha_cese %}
       {{object.fecha_cese}}
      {% else %}
        -------
      {% endif %}
    </p>
  </div>
</div>
<!-- Datos - Usuario -->
<div class="border-bottom-red-1">
  <h3 class="rotulo upper-case color-white text-shadow-black padding-normal-up-down">
    Datos Usuarios
  </h3>
</div>
<div class="group-detalle">
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Nombre de usuario
    </p>
    <p class="detalle-item-value font-weight-bolder ">
      @{{object.usuario.username}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
    Correo electrónico (Institucional)
    </p>
    <p class="detalle-item-value font-weight-bolder ">
      {{object.usuario.email}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Contraseña
      {% if object.usuario == instance.usuario %}
        <a href="{%url "usuario:password_change" object.usuario.slug %}" class="link color-red"> (Cambiar) </a>
      {% endif %}
    </p>
    <p class="detalle-item-value font-weight-bolder">
      {{object.usuario.password}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
        Número Tarjeta Mágnetica
    </p>
    <p class="detalle-item-value font-weight-bolder">
      {{object.usuario.numero_tarjeta_magnetica}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
        Número Acesso Biométrico
    <p class="detalle-item-value font-weight-bolder">
      {{object.usuario.numero_acceso_biometrico}}
    </p>
  </div>
</div>
<!-- Datos - Extras -->
<div class="border-bottom-red-1">
  <h3 class="rotulo upper-case color-white text-shadow-black padding-normal-up-down">
    Datos Extras
  </h3>
</div>
<div class="group-detalle">
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Teléfono (Personal)
    </p>
    <p class="detalle-item-value font-weight-bolder ">
        {% if object.fecha_cese %}
          {{object.telefono}}
        {% else %}
          -------
        {% endif %}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Celular (Personal)
    </p>
    <p class="detalle-item-value font-weight-bolder ">
        {% if object.fecha_cese %}
          {{object.celular}}
        {% else %}
          -------
        {% endif %}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Correo Electrónico (Personal)
    </p>
    <p class="detalle-item-value font-weight-bolder ">
        {% if object.email %}
          {{object.email}}
        {% else %}
          -------
        {% endif %}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Observación (Personal)
    </p>
    <p class="detalle-item-value font-weight-bolder ">
        {% if object.observacion_persona %}
          {{object.observacion_persona}}
        {% else %}
          -------
        {% endif %}
    </p>
  </div>
</div>
{% endblock detalle_right_container %}

empleados/templates/empleado_table.html
{% for object in object_list%}
<tr class="table-body-row" id="table_body_row">
  <td class="table-body-row-data"><input type="checkbox" id="ck_{{object.id}}"></td>
  <td class="table-body-row-data"><a href="{% url "empleado:detail" object.slug %}" class="link color-celeste">{{object.get_nombre_completo}}</a></td>
  <td class="table-body-row-data">{{ object.usuario }}</td>
  <td class="table-body-row-data">{{ object.usuario.email }}</td>
  <td class="table-body-row-data">{{ object.documento_identificacion }}</td>
  <td class="table-body-row-data">{{ object.numero_documento_identificacion }}</td>
  <td class="table-body-row-data">{{ object.area }}</td>
  <td class="table-body-row-data">{{ object.tipo_empleado }}</td>
  <td class="table-body-row-data">{{ object.cargo }}</td>
  <td class="table-body-row-data">
  	{% if object.fecha_registro %}
  		{{object.fecha_registro|date:"d/m/Y h:m:s"}}
  	{% else %}
  		-------
  	{% endif %}
  </td>
  {% if object.activo %}
    <td class="table-body-row-data color-verde-pastel text-center font-weight-bolder icon-circle-check "></td>
  {% else %}
    <td class="table-body-row-data color-red text-center font-weight-bolder icon-circle-cross "></td>
  {% endif%}
</tr>
{%endfor%}