app_navidad/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

from usuarios.views import UsuarioViewSet, PermissionViewSet, GroupViewSet, ContentTypeViewSet
from documentos_identificaciones.views import DocumentoIdentificacionViewSet
router = routers.DefaultRouter()
router.register(r'usuarios', UsuarioViewSet)
router.register(r'permissions', PermissionViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'content_type', ContentTypeViewSet)
router.register(r'documentos_identificaciones', DocumentoIdentificacionViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',                           include('catalogos_modulos_menus_sub_menus.urls', namespace='catalogo_modulo_menu_sub_menu')),
    url(r'^', 	                        include('usuarios.urls', namespace='usuario')),
    url(r'^', 	                        include('empleados.urls', namespace='empleado')),
    url(r'^empadronamiento-municipal/', 	                        include('empadronados.urls', namespace='empadronado')),
    #REST
    url(r'^api/', 						include(router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleados/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^empleado/nuevo/$', views.EmpleadoCreateView.as_view(), name='create'),
    #url(r'^empleado/(?P<slug>[-\w\W\d]+)/modificar/$', views.EmpleadoUpdateView.as_view(), name='update'),
    url(r'^empleado/(?P<slug>[-\w\W\d]+)/modificar/$', views.EmpleadoUpdate.as_view(), name='update'),
    url(r'^empleado/(?P<slug>[-\w\W\d]+)/$', views.EmpleadoDetailView.as_view(), name='detail'),
    url(r'^empleados/$', views.EmpleadoControlListView.as_view(), name='control'),
    url(r'^empleados/(?P<search_registro>[-\w\W\d]+)/$', views.EmpleadoControlListView.as_view(), name='control'),
]

usuarios/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url, include
from . import views
from django.contrib.auth.views import password_reset
from django.contrib.auth.views import password_reset_confirm
from django.contrib.auth.views import password_reset_complete
from django.contrib.auth.views import password_reset_done
from django.contrib.auth.views import password_change
from django.contrib.auth.views import password_change_done
from django.core.urlresolvers  import reverse_lazy


urlpatterns = [
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^usuario/(?P<slug>[-\w\W\d]+)/cambiar-contraseña/$', views.usuario_password_change, name='password_change'),
    #url(r'^control-de-asistencia/usuario/(?P<slug>[-\w\W\d]+)/cambiar-contraseña/done/$', views.usuario_password_change_done, name='password_change_done'),

    url(r'^restablecer-contraseña/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
            views.usuario_password_reset_confirm, name='password_reset_confirm'),
    url(r'^restablecer-contraseña/$', views.usuario_password_reset, name='password_reset'),
]

usuarios/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

#from password_reset.forms import PasswordRecoveryForm, PasswordResetForm
from .models import Usuario
from django.core.mail import send_mail
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)


class UsuarioModelForm(UserCreationForm):

	password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput(attrs={'class':'input-field-default'}))
	password2 = forms.CharField(label="Contraseña (Confirmar)", widget=forms.PasswordInput(attrs={'class':'input-field-default'}))

	class Meta():
		model  = Usuario
		fields = ['username', 'email' ,'numero_tarjeta_magnetica', 'numero_acceso_biometrico', ]

		widgets = {
			'username'    				   : forms.TextInput(attrs={'class':'input-field-default'}),
			'password1'    				   : forms.TextInput(attrs={'class':'input-field-default'}),
			'password2'    				   : forms.TextInput(attrs={'class':'input-field-default'}),
			'email'	  					   : forms.EmailInput(attrs={'class':'input-field-default', 'placeholder':'example@example.com'}),
			'numero_tarjeta_magnetica'	   : forms.NumberInput(attrs={'class':'input-field-default'}),
			'numero_acceso_biometrico'	   : forms.NumberInput(attrs={'class':'input-field-default'}),

        }


class UsuarioAuthenticationForm(AuthenticationForm):
	username = forms.CharField(
	        max_length=255,
	        widget=forms.TextInput(attrs={
	        							  'class'		: 'input-field-default',
	        							 }
	        					  ),
	    )
	password = forms.CharField(
			label=("Password"),
			strip=False,
			widget=forms.PasswordInput(attrs={
				 							  'class': 'input-field-default',
											  })
			)

usuarios/views.py
# -*- encoding: utf-8 -*-
from django.conf import settings
from django.http import Http404, HttpResponse
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash

from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.debug import sensitive_post_parameters
from pure_pagination.mixins import PaginationMixin
from django.shortcuts import render
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import FormView
from django.views.generic import TemplateView
from django.views.generic import View
from django.views.generic import RedirectView


from braces.views import LoginRequiredMixin, RecentLoginRequiredMixin

from .models import Usuario
from .serializers import UsuarioSerializer, PermissionSerializer, GroupSerializer, ContentTypeSerializer
from .forms import UsuarioModelForm, UsuarioAuthenticationForm

from django.core.urlresolvers import reverse_lazy
from rest_framework import viewsets
from django.db.models import Q
import socket
from django.contrib.auth.views import password_reset, password_reset_confirm, password_reset_done, password_change, password_change_done
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash

from infos_sistemas.mixins import tipo_perfil_usuario_mixin


def usuario_password_change(request, slug):
    instance = tipo_perfil_usuario_mixin(request)
    return password_change(request,
                        template_name='password_change.html',
                        post_change_redirect=reverse_lazy("empleado:detail", kwargs = {'slug' : instance.slug, }),
                        password_change_form=PasswordChangeForm,
                        extra_context={'username':request.user.username,
                                       'instance':instance}
                    )


def usuario_password_change_done(request, slug):
    instance = tipo_perfil_usuario_mixin(request)
    return password_change_done(request,
                        template_name='password_change_done.html',
                        extra_context={'username':request.user.username,
                                       'instance':instance}
                    )

def usuario_password_reset_confirm(request, uidb64=None, token=None):
    return password_reset_confirm(request, template_name='password_reset_confirm.html',
        uidb64=uidb64, token=token, post_reset_redirect=reverse_lazy('usuario:login'))


def usuario_password_reset(request):
    return password_reset(request, template_name='password_reset.html',
        email_template_name='password_reset_email.html',
        subject_template_name='password_reset_subject.txt',
        post_reset_redirect=reverse_lazy('usuario:login'))


class LoginView(FormView):
    form_class    =  UsuarioAuthenticationForm
    template_name = 'login.html'
    success_url   =  reverse_lazy('catalogo_modulo_menu_sub_menu:main')

    def form_valid(self, form):
        auth_login(self.request, form.get_user())
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()
        return super(LoginView, self).form_valid(form)

    def form_invalid(self, form):
        return super(LoginView, self).form_invalid(form)

    @method_decorator(sensitive_post_parameters('password'))
    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()
        return super(LoginView, self).dispatch(request, *args, **kwargs)


class LogoutView(RedirectView):
    url = reverse_lazy('usuario:login')
    def get(self, request, *args, **kwargs):
        auth_logout(self.request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class UsuarioCreateView(CreateView):
    template_name = 'usuario_create.html'
    form_class    = UsuarioModelForm
    success_url   = reverse_lazy('usuario:control')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.usuario_creador      = self.request.user
        self.object.ultimo_usuario_editor = self.object.usuario_creador
        try:
            self.object.nombre_host = socket.gethostname()
            self.object.ultimo_nombre_host = self.object.nombre_host
        except:
           self.object.nombre_host  = 'localhost'
           self.object.ultimo_nombre_host = self.object.nombre_host
        self.object.direccion_ip    = socket.gethostbyname(socket.gethostname())
        self.object.ultimo_direccion_ip =  socket.gethostbyname(socket.gethostname())
        self.object.save()

        return super(UsuarioCreateView, self).form_valid(form)

    def get_context_data(self, **kwarg):
        context     = super(UsuarioCreateView, self).get_context_data(**kwarg)
        is_auth  = False
        username = None
        id_usuario = None
        avatar = None
        if self.request.user.is_authenticated():
            id_usuario  = self.get_user_id()
            is_auth     = True
            username    = self.get_username()
            avatar      = self.get_avatar()
        data = {
            'id_usuario' : id_usuario,
            'is_auth'    : is_auth,
            'username'   : username,
            'avatar'     : avatar
        }
        context.update(data)
        return context

    def get_user_id(self):
        return self.request.user.id

    def get_username(self):
        return self.request.user.username

    def get_avatar(self):
        return self.request.user.avatar


class UsuarioUpdateView(UpdateView):
    form_class      = UsuarioModelForm
    success_url     = reverse_lazy('usuario:control')
    template_name   = 'usuario_update.html'
    queryset        = Usuario.objects.all()

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.ultimo_usuario_editor = self.request.user
        try:
            self.object.ultimo_nombre_host = socket.gethostname()
        except:
           self.object.ultimo_nombre_host  = 'localhost'

        self.object.ultimo_direccion_ip    = socket.gethostbyname(socket.gethostname())
        self.object.save()

        return super(UsuarioUpdateView, self).form_valid(form)

    def get_context_data(self, **kwarg):
        context     = super(UsuarioUpdateView, self).get_context_data(**kwarg)
        is_auth  = False
        username = None
        password = None

        if self.request.user.is_authenticated():
            id_usuario  = self.get_user_id()
            is_auth     = True
            username    = self.get_username()
            password    = self.get_password()

        data = {
            'id_usuario' : id_usuario,
            'is_auth'    : is_auth,
            'username'   : username,
            'password'   : password,
        }

        context.update(data)
        return context

    def get_user_id(self):
        return self.request.user.id

    def get_password(self):
        return self.request.user.password

    def get_username(self):
        return self.request.user.username


class UsuarioControlListView(PaginationMixin, ListView):
    model         = Usuario
    template_name = 'usuarios.html'
    paginate_by   = 10

    def get_context_data(self, **kwarg):
        context     = super(UsuarioControlListView, self).get_context_data(**kwarg)
        is_auth  = False
        username = None
        id_usuario = None
        boton_menu     = False
        total_registro = self.model.objects.count()
        avatar = None

        if self.request.user.is_authenticated():
            id_usuario  = self.get_user_id()
            is_auth     = True
            username    = self.get_username()
            avatar      = self.get_avatar()
        data = {
            'id_usuario'    : id_usuario,
            'is_auth'       : is_auth,
            'username'      : username,
            'boton_menu'    : boton_menu,
            'total_registro': total_registro,
            'avatar'        : avatar,
        }

        context.update(data)
        return context

    def get_user_id(self):
        return self.request.user.id

    def get_username(self):
        return self.request.user.username

    def get_avatar(self):
        return self.request.user.avatar

    def get_template_names(self):
        if self.request.GET.get('search_registro', None) != None:
            return "empleado_table.html"
        else:
            return self.template_name

    def get(self, request, *args, **kwargs):
        if request.GET.get('search_registro', None):
            self.object_list = self.get_queryset()
            context = self.get_context_data()
            return self.render_to_response(context)
        else:
            return super(UsuarioControlListView, self).get(self, request, *args, **kwargs)

    def get_queryset(self):
        if self.kwargs.get('variable'):
            queryset = self.model.objects.filter(slug__icontains=self.kwargs['variable'])

        elif self.request.GET.get('search_registro', ''):
            queryset = self.model.objects.filter(
                        Q(slug__icontains=self.request.GET.get('search_registro', ''))
                        |Q(email__icontains=self.request.GET.get('search_registro', ''))
                        |Q(pk__icontains=self.request.GET.get('search_registro', ''))
                    )
        else:
            queryset = super(UsuarioControlListView, self).get_queryset()
        return queryset


class UsuarioDetailView(DetailView):

usuarios/templates/base.html
{% extends 'base_main_modulo_nav.html '%}

usuarios/templates/login.html
{% extends 'base_main_modulo.html'%}
{% load static from staticfiles %}
{% block title %}
	Iniciar Sesión | Log In
{% endblock title %}

{% block section %}
<!-- Login -->
<article class="login">
	<!-- Saludo -->
	<div class="container border-bottom-red-1">
		<p class="titulo padding-full color-white text-shadow-black font-weight-bolder">
			Bienvenidos
		</p>
		<p class="sub-rayado background-red">

		</p>
	</div>
	<!-- Container Form -->
	<div class="flex-full-center padding-full-max-up-down padding-full">
		<!-- Formulario -->
		<form action="" method="post" class="form padding-normal-left-right position-relative box-shadow-black border-radius-small border-top-black-1  border-bottom-black-1" id="form_login">
			{% csrf_token %}
			<!-- Form - Head -->
			<div class="form-head">
				<!-- Avatar -->
				<div class="logo_avatar">
					<figure>
						<img class=" background-verde-pastel box-shadow-black radius-circular border-black-2" src="{% static "imagenes/png/Robot_1.png"%}" alt="">
					</figure>
				</div>
				<div class="container margin-login">
					<p class="rotulo text-center color-azul font-weight-bolder ">
						Iniciar Sesión | Log In
					</p>
				</div>
			</div>
			<!-- Form - Body -->
			<div class="form-body">
				<!-- Usuario -->
				<div class="componente">
					<!-- Field -->
					<div class="field">
						<!-- Label -->
						<div class="container-label">
							<label for="{{ form.username.auto_id }}" class="label font-weight-bolder">
							{{form.username.label}}
							</label>
						</div>
						<!-- Input -->
						<div class="input">
							{{form.username}}
						</div>
					</div>
					<!-- Error -->
					<div class="error">
						{{form.username.errors}}
					</div>
				</div>
				<!-- Password -->
				<div class="componente">
					<!-- Field -->
					<div class="field">
						<!-- Label -->
						<div class="container-label">
							<label for="{{ form.password.auto_id }}" class="label font-weight-bolder">
							{{form.password.label}}
							</label>
						</div>
						<!-- Input -->
						<div class="input">
							{{form.password}}
						</div>
					</div>
					<!-- Error -->
					<div class="error">
						{{form.password.errors}}
					</div>
				</div>
				<!-- Submit -->
				<div class="componente">
					<div class="container-submit background-verde-pastel ">
						<input type="submit" class="submit color-white text-shadow-black ">
					</div>
				</div>
				<!-- Olvidaste tu contraseña -->
				<div class="field">
					<div class="input margin-auto-left-right">
						<a href="{% url "usuario:password_reset" %}" class="link display-block color-red text-center">
							¿Olvidastes tu contraseña?
						</a>
					</div>
				</div>
			</div>
			<!-- Form - Footer -->
			<div class="form-footer">
				<!-- Mensaje Errores -->
				<div class="mensajeError">
					<p class="textError color-azul font-size-text">
						{% if form.non_field_errors %}
							  {% for err in form.non_field_errors %}
							 	 {{ err }}
							  {% endfor %}
						{% endif %}
					</p>
				</div>
			</div>
		</form>

	</div>
	<div class="nota margin-auto-left-right">
    <p class="text-center">
			Enviar sus consultas a la Sub Gerencia de Tecnología de la Información mediante el correo electrónico:
			<span class="font-weight-bolder">tecnologia.informacion@munisanandres.gob.pe</span>
    </p>
  </div>
</article>
{% endblock section %}

{% block script_template %}
	<script id ="login_template" type="text/template">

	</script>
{% endblock script_template %}

usuarios/templates/password_change.html
{% extends 'base_main_modulo_nav.html '%}

{% load static from staticfiles %}
{% load widget_tweaks %}

{% block title %}
	Control de Asistencia | Cambiar Contraseña
{% endblock title %}

{% block src_avatar_modulo %} {% static "imagenes/png/Control_Asistencia_1.png"%} {% endblock src_avatar_modulo %}"
{% block alt_avatar_modulo %} Control de Asistencia {% endblock alt_avatar_modulo %}"

{% block nav-border %}
	border-bottom-red-1
{% endblock nav-border %}

{% block section %}
<!-- Login -->
<article class="container padding-full">
	<!-- Container Form -->
	<div class="flex-full-center">
		<!-- Formulario -->
		<form action="" method="post" class="form position-relative " id="form">
			{% csrf_token %}
			<div class="form-head padding-normal-up-down border-bottom-red-2">
				<h3 class="rotulo upper-case color-white text-shadow-black">
					Cambiar Contraseña
				</h3>
			</div>
			<!-- Form - Body -->
			<div class="form-body padding-normal-up-down">
				<!-- Contraseña Antigua -->
				<div class="componente">
					<!-- Field -->
					<div class="field">
						<!-- Label -->
						<div class="container-label">
							<label for="{{ form.old_password.auto_id }}" class="label font-weight-bolder">
							{{form.old_password.label}}
							</label>
						</div>
						<!-- Input -->
						<div class="input">
							{{form.old_password|attr:"class:input-field-default"}}
						</div>
					</div>
					<!-- Error -->
					<div class="error">
						{{form.old_password.errors}}
					</div>
				</div>
				<!-- Contraseña Nueva -->
				<div class="componente">
					<!-- Field -->
					<div class="field">
						<!-- Label -->
						<div class="container-label">
							<label for="{{ form.new_password1.auto_id }}" class="label font-weight-bolder">
							{{form.new_password1.label}}
							</label>
						</div>
						<!-- Input -->
						<div class="input">
							{{form.new_password1|attr:"class:input-field-default"}}

						</div>
					</div>
					<!-- Error -->
					<div class="error">
						{{form.new_password1.errors}}
					</div>
				</div>
				<!-- Contraseña Nueva Confirmar -->
				<div class="componente">
					<!-- Field -->
					<div class="field">
						<!-- Label -->
						<div class="container-label">
							<label for="{{ form.new_password2.auto_id }}" class="label font-weight-bolder">
							{{form.new_password2.label}}
							</label>
						</div>
						<!-- Input -->
						<div class="input">
							{{form.new_password2|attr:"class:input-field-default"}}
						</div>
					</div>
					<!-- Error -->
					<div class="error">
						{{form.new_password2.errors}}
					</div>
				</div>
			</div>
			<!-- Submit -->
			<div class="componente">
				<div class="container-submit background-red ">
					<input type="submit" class="submit color-white text-shadow-black" value="Guardar Cambios">
				</div>
			</div>
		</form>
	</div>
</article>
{% endblock section %}

usuarios/templates/password_reset.html
{% extends 'base_main_modulo.html '%}
{% load static from staticfiles %}
{% load widget_tweaks %}
{% block title %} Restablecer Contraseña {% endblock %}

{% block section %}
<!-- Recuperar Contraseña -->
<article class="container padding-full">
	<!-- Saludo -->
	<div class="container border-bottom-red-1">
		<p class="titulo padding-full color-white text-shadow-black font-weight-bolder">
			Bienvenidos
		</p>
		<p class="sub-rayado background-red">

		</p>
	</div>
	<!-- Container Form -->
	<div class="flex-full-center padding-full-max-up-down padding-full">
		<!-- Formulario -->
		<form action="" method="post" class="form padding-full position-relative box-shadow-black border-radius-small border-top-black-1  border-bottom-black-1" id="form_login">
			{% csrf_token %}
			<!-- Form - Head -->
			<div class="form-head">
				<!-- Avatar -->
				<div class="logo_avatar">
					<figure>
						<img class=" background-white box-shadow-black radius-circular border-black-2" src="{% static "imagenes/png/Email_1.png"%}" alt="">
					</figure>
				</div>
				<div class="container margin-login">
					<p class="rotulo text-center color-azul font-weight-bolder ">
						Restablecer Contraseña
					</p>
				</div>
			</div>
			<!-- Form - Body -->
			<div class="form-body">
				<!-- Usuario -->
				<div class="componente">
					<!-- Field -->
					<div class="field">
						<!-- Label -->
						<div class="container-label">
							<label for="{{ form.email.auto_id }}" class="label font-weight-bolder">
							{{form.email.label}}
							</label>
						</div>
						<!-- Input -->
						<div class="input">
							{{form.email|attr:"class:input-field-default"}}
						</div>
					</div>
					<!-- Error -->
					<div class="error">
						{{form.email.errors}}
					</div>
				</div>

				<!-- Submit -->
				<div class="componente">
					<div class="container-submit background-verde-pastel ">
						<input type="submit" class="submit color-white text-shadow-black ">
					</div>
				</div>
      </div>
			<!-- Form - Footer -->
			<div class="form-footer">
				<!-- Mensaje Errores -->
				<div class="mensajeError">
					<p class="textError color-azul font-size-text">
						Ingresar el correo electrónico asociado a su usuario, se le enviará un mensaje con un link web
            indicando como ud. podra restablecer su contraseña.
					</p>
				</div>
			</div>
		</form>
	</div>
  <div class="nota margin-auto-left-right">
    <p class="text-center">
      <span class="color-red font-weight-bolder">Nota:</span>
      El link web es unico y tiene un periódo de caducidad.
    </p>
  </div>
</article>
{% endblock section %}

usuarios/templates/password_reset_confirm.html
{% extends 'base_main_modulo.html '%}
{% block title %} Nueva Contraseña {% endblock %}
{% load widget_tweaks %}

{% block section %}
  {% if validlink %}
     <article class="container flex-direction-column padding-full">
     	<!-- Container Form -->
     	<div class="flex-full-center ">
     		<!-- Formulario -->
     		<form action="" method="post" class="form position-relative " id="form">
     			{% csrf_token %}
     			<div class="form-head padding-normal-up-down border-bottom-red-2">
     				<h3 class="rotulo upper-case color-white text-shadow-black">
     					Nueva Contraseña
     				</h3>
     			</div>
     			<!-- Form - Body -->
     			<div class="form-body padding-normal-up-down">
     				<!-- Contraseña Nueva -->
     				<div class="componente">
     					<!-- Field -->
     					<div class="field">
     						<!-- Label -->
     						<div class="container-label">
     							<label for="{{ form.new_password1.auto_id }}" class="label font-weight-bolder">
     							{{form.new_password1.label}}
     							</label>
     						</div>
     						<!-- Input -->
     						<div class="input">
     							{{form.new_password1|attr:"class:input-field-default"}}
     						</div>
     					</div>
     					<!-- Error -->
     					<div class="error">
     						{{form.new_password1.errors}}
     					</div>
     				</div>
     				<!-- Contraseña Nueva Confirmar -->
     				<div class="componente">
     					<!-- Field -->
     					<div class="field">
     						<!-- Label -->
     						<div class="container-label">
     							<label for="{{ form.new_password2.auto_id }}" class="label font-weight-bolder">
     							{{form.new_password2.label}}
     							</label>
     						</div>
     						<!-- Input -->
     						<div class="input">
     							{{form.new_password2|attr:"class:input-field-default"}}
     						</div>
     					</div>
     					<!-- Error -->
     					<div class="error">
     						{{form.new_password2.errors}}
     					</div>
     				</div>
          </div>
          <!-- Submit -->
     			<div class="componente">
     				<div class="container-submit background-red ">
     					<input type="submit" class="submit color-white text-shadow-black" value="Guardar Cambios">
     				</div>
     			</div>
     		</form>
     	</div>

      <div class="nota margin-auto-left-right">
        <p class="text-center">
          Enviar sus consultas a la Sub Gerencia de Tecnología de la Información mediante el correo electrónico:
          <span class="font-weight-bolder">tecnologia.informacion@munisanandres.gob.pe</span>
        </p>
      </div>
    </article>
  {% else %}
     <h1>Password reset unsuccessful</h1>
     <p>The password reset link was invalid, <br />
     possibly because it has already been used. <br />
     Please request a new password reset.</p>
  {% endif %}
{% endblock %}

usuarios/templates/password_reset_email.html
{% autoescape off %}
You're receiving this e-mail because you requested a password reset for your user account at {{ site_name }}.

Please go to the following page and choose a new password:
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url "usuario:password_reset_confirm" uidb64=uid token=token %}
{% endblock %}

Your username, in case you've forgotten: {{ user.username }}

Thanks for using our site!

The {{ site_name }} team.

{% endautoescape %}

usuarios/templates/usuario_table.html
{% for object in object_list%}
<tr  class="table-body-row" id="table_body_row">
	<td class="table-body-row-data"><input type="checkbox" id="ck_{{object.id}}"></td>
    <td class="table-body-row-data"><a href="{% url "usuario:update" object.slug %}" class="link color-celeste">{{object.username}}</a></td>
    <td class="table-body-row-data">{{ object.email }}</td>
    <td class="table-body-row-data">{{ object.numero_tarjeta_magnetica }}</td>
    <td class="table-body-row-data">{{ object.numero_acceso_biometrico }}</td>
    <td class="table-body-row-data">{{ object.is_active }}</td>
	<td class="table-body-row-data">{{ object.is_staff }}</td>
	<td class="table-body-row-data">{{ object.is_superuser }}</td>
	<td class="table-body-row-data">
		{% if object.last_login %}
			{{object.last_login|date:"d/m/Y h:m:s"}}
		{% else %}
			-------
		{% endif %}
	</td>

	<td class="table-body-row-data">
		{% if object.fecha_registro %}
			{{object.fecha_registro|date:"d/m/Y h:m:s"}}
		{% else %}
			-------
		{% endif %}
	</td>

</tr>
{%endfor%}

usuarios/templates/usuarios.html
{% extends 'base_main_modulo_menu_control.html' %}
{% load static from staticfiles %}
{% block title %} 
	Control de Asistencia | Usuario
{% endblock title %}

{% block src_avatar_modulo %} {% static "imagenes/png/Control_Asistencia_1.png"%} {% endblock src_avatar_modulo %}" 
{% block alt_avatar_modulo %} Control de Asistencia {% endblock alt_avatar_modulo %}"

{% block nav-border %} 
	border-bottom-red-1 
{% endblock nav-border %}


{% block panel_nombre_menu %} Usuario {% endblock panel_nombre_menu%}

{% block background_agregar_movil %} background-red {% endblock background_agregar_movil %}
{% block background_agregar_desktop %} background-red {% endblock background_agregar_desktop %} 

{% block url_agregar_registro_movil %} {% url "usuario:create" %} {% endblock url_agregar_registro_movil %}
{% block url_agregar_registro_desktop %} {% url "usuario:create" %} {% endblock url_agregar_registro_desktop %}

{% block background_table_head %} background-red {% endblock background_table_head %}
{% block background_paginas %} background-red {% endblock background_paginas %}

{% block background_eliminar_movil %} background-red {% endblock background_eliminar_movil %}
{% block background_eliminar_desktop %} background-red {% endblock background_eliminar_desktop %}

{% block background_search_pagina_submit %} background-red {% endblock background_search_pagina_submit %}

{% block script_template %}
	<script id ="input_search_registro_template" type="text/template">
		<input type="search" id="input_search_registro" class="input-field-default">
	</script>
{% endblock script_template %}