app_navidad/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

from usuarios.views import UsuarioViewSet, PermissionViewSet, GroupViewSet, ContentTypeViewSet
from documentos_identificaciones.views import DocumentoIdentificacionViewSet
router = routers.DefaultRouter()
router.register(r'usuarios', UsuarioViewSet)
router.register(r'permissions', PermissionViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'content_type', ContentTypeViewSet)
router.register(r'documentos_identificaciones', DocumentoIdentificacionViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',                           include('catalogos_modulos_menus_sub_menus.urls', namespace='catalogo_modulo_menu_sub_menu')),
    url(r'^', 	                        include('usuarios.urls', namespace='usuario')),
    url(r'^', 	                        include('empleados.urls', namespace='empleado')),
    url(r'^empadronamiento-municipal/', 	                        include('empadronados.urls', namespace='empadronado')),
    #REST
    url(r'^api/', 						include(router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogos_modulos_menus_sub_menus/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^modulos/$', views.CatalagoModuloMenuTemplateView.as_view(), name='main'),
    url(r'^empadronamiento-municipal/$', views.EmpadronamientoMunicipalTemplateView.as_view(), name='empadronamiento_municipal'),
    url(r'^empadronamiento-municipal/menu/$', views.EmpadronamientoMunicipalMenuTemplateView.as_view(), name='empadronamiento_municipal_menu'),
]

empadronados/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^empadronado/nuevo/$', views.EmpadronadoCreateView.as_view(), name='create'),
    url(r'^verificar/empadronado/$', views.EmpadronadoSearchQRListView.as_view(), name='codigo_barra_qr'),
    url(r'^empadronado/(?P<slug>[-\w\W\d]+)/modificar/$', views.EmpadronadoUpdateView.as_view(), name='update'),
    url(r'^empadronados/$', views.EmpadronadoControlListView.as_view(), name='control'),
    url(r'^empadronados/(?P<search_registro>[-\w\W\d]+)/$', views.EmpadronadoControlListView.as_view(), name='control'),
    url(r'^empadronado/(?P<slug>[-\w\W\d]+)/$', views.EmpadronadoDetailView.as_view(), name='detail'),
    url(r'^empadronado/(?P<slug>[-\w\W\d]+)/imprimir$', views.EmpadronadoPrintTicketDetailView.as_view(), name='print'),
    url(r'^reportes$', views.EmpadronadoReportListView.as_view(), name='report'),


]

usuarios/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url, include
from . import views
from django.contrib.auth.views import password_reset
from django.contrib.auth.views import password_reset_confirm
from django.contrib.auth.views import password_reset_complete
from django.contrib.auth.views import password_reset_done
from django.contrib.auth.views import password_change
from django.contrib.auth.views import password_change_done
from django.core.urlresolvers  import reverse_lazy


urlpatterns = [
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^usuario/(?P<slug>[-\w\W\d]+)/cambiar-contraseña/$', views.usuario_password_change, name='password_change'),
    #url(r'^control-de-asistencia/usuario/(?P<slug>[-\w\W\d]+)/cambiar-contraseña/done/$', views.usuario_password_change_done, name='password_change_done'),

    url(r'^restablecer-contraseña/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
            views.usuario_password_reset_confirm, name='password_reset_confirm'),
    url(r'^restablecer-contraseña/$', views.usuario_password_reset, name='password_reset'),
]

empadronados/models.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

from infos_sistemas.models import InfoSistema
from django.template.defaultfilters import slugify

from personas.models import Persona
from cargos.models import Cargo
from grados_instrucciones.models import GradoInstruccion
from tipos_empleados.models import TipoEmpleado
from profesiones.models import Profesion
from ocupaciones.models import Ocupacion
from usuarios.models import Usuario
from areas.models import Area
from infos_sistemas.validators import valid_extension
import datetime
import math

class Empadronado(Persona):
	BOOL_ACTIVO 		 			= ((True, 'Si'), (False, 'No'))
	descripcion_empadronado		    = models.TextField(verbose_name='Descripción (Empadronado)' ,blank=True, null=True, help_text='(Opcional).')
	observacion_empadronado			= models.TextField(verbose_name='Observación (Empadronado)' ,blank=True, null=True, help_text='(Opcional).')
	codigo_barra_qr    			    = models.ImageField(
															blank=True,
															null=True,
															verbose_name='QR (Fotografía)',
															upload_to='empadronado_codigo_barra_qr',
															help_text='Subir Código Barra QR (Opcional).',
															default='default/No_Avatar_1.png',
															validators=[valid_extension]
														)
	numero_ticket						= models.PositiveSmallIntegerField(
																		default = 0,
																		unique=True,
																		verbose_name='Número Ticket',
																		)



	activo 							= models.BooleanField(choices=BOOL_ACTIVO, default=True)

		#Métodos
	#Python 3.X
	def __str__(self):
		return self.get_nombre_completo()

	#Python 2.X
	#def __unicode__(self):
	#	return self.nombre
	def id_empadronado(self):
		return str(self.id).zfill(10)

	def edad(self):
		fecha_nacimiento = self.fecha_nacimiento
		fecha_actual = datetime.datetime.now().date()
		diferencia_fecha = fecha_actual - fecha_nacimiento
		edad = math.floor(diferencia_fecha.days/365.25)
		return edad

	def rango_edad(self):
		edad = self.edad()
		if edad >= 0 and edad<=3:
			return "0 - 3"
		elif edad >= 4 and edad<=7:
			return "4 - 7"
		elif edad >= 8 and edad<=10:
			return "8 - 10"

	def save(self, *args, **kwargs):
		if not self.pk:
			self.slug = slugify(self.get_nombre_completo())
		else:
			slug = slugify(self.get_nombre_completo())
			if self.slug != slug:
				self.slug = slug
		super(Empadronado, self).save(*args, **kwargs)

	#Opciones
	class Meta:
		#Nombre para la tabla del gestor de base de datos
		db_table = 'Empadronados'
		#Ordenar los registros por un campo especifico
		ordering = ('apellido_paterno',)
		#Nombre para el Conjunto de Objetos en el Panel de Administración
		verbose_name = 'Empadronado'
		#Nombre en Plural en la lista de módulos en el Panel de Administración
		verbose_name_plural = 'Empadronados'#Métodos

empadronados/views.py
# -*- encoding: utf-8 -*-
from django.conf import settings
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from .models import Empadronado
from .forms import EmpadronadoModelForm
from django.core.urlresolvers import reverse_lazy
from rest_framework import viewsets
from django.db.models import Q
import socket
from pure_pagination.mixins import PaginationMixin
from django.template.defaultfilters import slugify
from infos_sistemas.mixins import TipoPerfilUsuarioMixin
import datetime
import qrcode
from django.core.files import File
import os
from .mixins import AccessUserRequiredMixin


class EmpadronadoCreateView(TipoPerfilUsuarioMixin, AccessUserRequiredMixin, CreateView):
    template_name = 'empadronado_create.html'
    model         = Empadronado
    success_url   = reverse_lazy('empadronado:control')
    form_class    = EmpadronadoModelForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.tipo_persona = 'Natural'
        if self.object.numero_hijo is None:
            self.object.numero_hijo = 0
        self.object.usuario_creador      = self.request.user
        self.object.ultimo_usuario_editor = self.object.usuario_creador
        try:
            self.object.nombre_host = socket.gethostname()
            self.object.ultimo_nombre_host = self.object.nombre_host
        except:
           self.object.nombre_host  = 'localhost'
           self.object.ultimo_nombre_host = self.object.nombre_host
        self.object.direccion_ip    = socket.gethostbyname(socket.gethostname())
        self.object.ultimo_direccion_ip =  socket.gethostbyname(socket.gethostname())
        self.object.save()
        #img_qr = qrcode.make(str(self.object.id).zfill(10))
        img_qr = qrcode.make(self.object.id)
        nombre_img_qr_extension = str(self.object.id).zfill(10)+".png"
        f = open(nombre_img_qr_extension, "wb")
        img_qr.save(f)
        f.close()
        reopen = open(nombre_img_qr_extension, "rb")
        django_file = File(reopen)
        self.object.codigo_barra_qr.save(nombre_img_qr_extension, django_file, save=True)
        reopen.close()
        self.object.save()
        os.remove(nombre_img_qr_extension)
        return super(EmpadronadoCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(EmpadronadoCreateView, self).get_context_data(**kwargs)
        boton_menu = True
        data = {
			'boton_menu':boton_menu,
			}
        context.update(data)
        return context


class EmpadronadoUpdateView(TipoPerfilUsuarioMixin, AccessUserRequiredMixin, UpdateView):
    form_class      = EmpadronadoModelForm
    success_url     = reverse_lazy('empadronado:control')
    template_name   = 'empadronado_update.html'
    queryset        = Empadronado.objects.all()

    def get_context_data(self, **kwargs):
        context = super(EmpadronadoUpdateView, self).get_context_data(**kwargs)
        boton_menu = True
        data = {
			'boton_menu':boton_menu,
			}
        context.update(data)
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if self.object.numero_hijo  is None:
            self.object.numero_hijo = 0
        self.object.ultimo_usuario_editor = self.request.user
        try:
            self.object.ultimo_nombre_host = socket.gethostname()
        except:
           self.object.ultimo_nombre_host  = 'localhost'

        self.object.ultimo_direccion_ip    = socket.gethostbyname(socket.gethostname())
        self.object.save()

        return super(EmpadronadoUpdateView, self).form_valid(form)


class EmpadronadoReportListView(PaginationMixin, TipoPerfilUsuarioMixin, AccessUserRequiredMixin, ListView):
    model         = Empadronado
    template_name = 'empadronado_report.html'
    paginate_by   = 25

    def get_context_data(self, **kwargs):
        context = super(EmpadronadoReportListView, self).get_context_data(**kwargs)
        boton_menu     = True
        total_registro = self.model.objects.count()
        total_masculino = self.model.objects.filter(Q(genero__icontains='Masculino')).count()
        total_femenino  = self.model.objects.filter(Q(genero__icontains='Femenino')).count()
        data = {
            'boton_menu'    : boton_menu,
            'total_registro': total_registro,
            'total_masculino' : total_masculino,
            'total_femenino' : total_femenino,
        }

        context.update(data)
        return context

    def get(self, request, *args, **kwargs):
        if  self.request.GET.get('radio_report', None) and self.request.GET.get('radio_genero', None):
            self.object_list = self.get_queryset()
            context = self.get_context_data()
            value = self.request.GET.get('radio_genero', None)
            select = self.request.GET.get('radio_report', None)
            if select == 'Todos':
                if value == 'Masculino':
                    context['total_masculino'] = self.model.objects.filter(Q(genero__icontains='Masculino')).count()
                    context['total_femenino'] = 0
                    context['total_registro'] = context['total_masculino']
                elif value == 'Femenino':
                    context['total_femenino'] = self.model.objects.filter(Q(genero__icontains='Femenino')).count()
                    context['total_masculino'] = 0
                    context['total_registro'] = context['total_femenino']
                elif value == 'General':
                    context['total_masculino'] = self.model.objects.filter(Q(genero__icontains='Masculino')).count()
                    context['total_femenino'] = self.model.objects.filter(Q(genero__icontains='Femenino')).count()
                    context['total_registro'] = self.model.objects.all().count()
            elif select == 'Fecha':
                input_fecha = self.request.GET.get('input_fecha', None)
                if value == 'Masculino':
                    context['total_masculino'] = self.model.objects.filter(Q(genero__icontains='Masculino') & Q(fecha_registro__icontains=input_fecha)).count()
                    context['total_femenino'] = 0
                    context['total_registro'] = context['total_masculino']
                elif value == 'Femenino':
                    context['total_femenino'] = self.model.objects.filter(Q(genero__icontains='Femenino') & Q(fecha_registro__icontains=input_fecha)).count()
                    context['total_masculino'] = 0
                    context['total_registro'] = context['total_femenino']
                elif value == 'General':
                    context['total_masculino'] = self.model.objects.filter(Q(genero__icontains='Masculino') & Q(fecha_registro__icontains=input_fecha)).count()
                    context['total_femenino'] = self.model.objects.filter(Q(genero__icontains='Femenino') & Q(fecha_registro__icontains=input_fecha)).count()
                    context['total_registro'] = context['total_masculino'] + context['total_femenino']
            elif select == 'Rango_Fecha':
                inicio_fecha = self.request.GET.get('inicio_fecha', None)
                fin_fecha = self.request.GET.get('fin_fecha', None)
                if value == 'Masculino':
                    context['total_masculino'] = self.model.objects.filter(Q(genero__icontains='Masculino') & Q(fecha_registro__range=[inicio_fecha, fin_fecha])).count()
                    context['total_femenino'] = 0
                    context['total_registro'] = context['total_masculino']
                elif value == 'Femenino':
                    context['total_femenino'] = self.model.objects.filter(Q(genero__icontains='Femenino') & Q(fecha_registro__range=[inicio_fecha, fin_fecha])).count()
                    context['total_masculino'] = 0
                    context['total_registro'] = context['total_femenino']
                elif value == 'General':
                    context['total_masculino'] = self.model.objects.filter(Q(genero__icontains='Masculino') & Q(fecha_registro__range=[inicio_fecha, fin_fecha])).count()
                    context['total_femenino'] = self.model.objects.filter(Q(genero__icontains='Femenino') & Q(fecha_registro__range=[inicio_fecha, fin_fecha])).count()
                    context['total_registro'] = context['total_masculino'] + context['total_femenino']

            elif self.request.GET.get('radio_report', None) == 'Rango_0_3':
                if value == 'Masculino':
                    context['total_masculino'] = self.model.objects.filter(Q(genero__icontains='Masculino') & Q(fecha_nacimiento__range=('2013-01-01', '2016-12-31'))).count()
                    context['total_femenino'] = 0
                    context['total_registro'] = context['total_masculino']
                elif value == 'Femenino':
                    context['total_femenino'] = self.model.objects.filter(Q(genero__icontains='Femenino') & Q(fecha_nacimiento__range=('2013-01-01', '2016-12-31'))).count()
                    context['total_masculino'] = 0
                    context['total_registro'] = context['total_femenino']
                elif value == 'General':
                    context['total_femenino'] = self.model.objects.filter(Q(genero__icontains='Femenino') & Q(fecha_nacimiento__range=('2013-01-01', '2016-12-31'))).count()
                    context['total_femenino'] = self.model.objects.filter(Q(genero__icontains='Femenino') & Q(fecha_nacimiento__range=('2013-01-01', '2016-12-31'))).count()
                    context['total_registro'] = context['total_masculino'] + context['total_femenino']

            elif self.request.GET.get('radio_report', None) == 'Rango_4_7':
                if value == 'Masculino':
                    context['total_masculino'] = self.model.objects.filter(Q(genero__icontains='Masculino') & Q(fecha_nacimiento__range=('2009-01-01', '2012-12-31'))).count()
                    context['total_femenino'] = 0

empadronados/templates/empadronado_detail.html
{% extends 'base_detail.html '%}
{% load static from staticfiles %}
{% block titulo_perfil %} Empadronado {% endblock titulo_perfil %}

{% block src_avatar_modulo %} {% static "imagenes/png/Navidad_1.png"%} {% endblock src_avatar_modulo %}"
{% block alt_avatar_modulo %} Empadronamiento Municipal {% endblock alt_avatar_modulo %}"
{% block url_menu_control %} {% url "catalogo_modulo_menu_sub_menu:empadronamiento_municipal_menu" %} {% endblock url_menu_control %}

{% block nav-border %}
	border-bottom-red-1
{% endblock nav-border %}

{% block detalle_left_container %}
<figure class="container ">
  <img class="imagen-perfil border-black-2 margin-auto-left-right background-white"
       src="{{object.fotografia.url}}"
       alt="{{object.get_nombre_completo}}"/>
  <figcaption class="detalle-nombre padding-normal-left-right">
    <a href="{% url "empadronado:update" object.slug %}" class="rotulo link padding-normal-up-down display-block text-center font-weight-bolder text-shadow-black">
      <p>
        {{object.nombre}}
      </p>
      <p>
        {{object.apellido_paterno}} {{object.apellido_materno}}
      </p>
    </a>
    <p class="text-center border-top-red-1  padding-normal-up-down color-gris-oscuro font-weight-bolder ">
        Código:{{object.id_empadronado}}
    </p>
  </figcaption>

  <div class="group-detalle">
    <div class="detalle-item">
      <p class="detalle-item-label font-weight-bolder">
        Descripción (Empadronado)
      <p class="detalle-item-area font-weight-bolder">
        {{object.descripcion_empadronado}}
      </p>
    </div>
  </div>

  <div class="group-detalle">
    <div class="detalle-item">
      <p class="detalle-item-label font-weight-bolder">
        Observación (Empadronado)
      <p class="detalle-item-area font-weight-bolder">
        {{object.observacion_empadronado}}
      </p>
    </div>
  </div>
</figure>
{% endblock detalle_left_container %}
{% block detalle_right_container %}
<div class="group-detalle">
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
        Documento identificación
    <p class="detalle-item-value font-weight-bolder">
      {{object.documento_identificacion}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
        Número documento identificación
    <p class="detalle-item-value font-weight-bolder">
      {{object.numero_documento_identificacion}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Fecha de nacimiento
    <p class="detalle-item-value font-weight-bolder">
      {{object.fecha_nacimiento}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Género
    <p class="detalle-item-value font-weight-bolder">
      {{object.genero}}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Estado civil
    <p class="detalle-item-value font-weight-bolder">
      {{object.estado_civil}}
    </p>
  </div>
</div>
<!-- Datos - Extras -->
<div class="border-bottom-red-1">
  <h3 class="rotulo upper-case color-white text-shadow-black padding-normal-up-down">
    Datos Extras
  </h3>
</div>
<div class="group-detalle">
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Teléfono (Personal)
    </p>
    <p class="detalle-item-value font-weight-bolder ">
        {% if object.fecha_cese %}
          {{object.telefono}}
        {% else %}
          -------
        {% endif %}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Celular (Personal)
    </p>
    <p class="detalle-item-value font-weight-bolder ">
        {% if object.fecha_cese %}
          {{object.celular}}
        {% else %}
          -------
        {% endif %}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Correo Electrónico (Personal)
    </p>
    <p class="detalle-item-value font-weight-bolder ">
        {% if object.email %}
          {{object.email}}
        {% else %}
          -------
        {% endif %}
    </p>
  </div>
  <div class="detalle-item">
    <p class="detalle-item-label font-weight-bolder">
      Observación (Personal)
    </p>
    <p class="detalle-item-value font-weight-bolder ">
        {% if object.observacion_persona %}
          {{object.observacion_persona}}
        {% else %}
          -------
        {% endif %}
    </p>
  </div>
</div>
{% endblock detalle_right_container %}

empadronados/templates/empadronado_table.html
{% for object in object_list%}
<tr class="table-body-row" id="table_body_row">
  <td class="table-body-row-data "><input type="checkbox" id="ck_{{object.id}}"></td>
  <td class="table-body-row-data text-center"><a href="{% url "empadronado:print" object.slug %}" class="link color-red icon-printer"> </a></td>
  <td class="table-body-row-data">{{ object.id_empadronado }}</td>
  <td class="table-body-row-data"><a href="{% url "empadronado:detail" object.slug %}" class="link color-celeste">{{object.get_nombre_completo}}</a></td>
  <td class="table-body-row-data">{{ object.documento_identificacion }}</td>
  <td class="table-body-row-data">{{ object.numero_documento_identificacion }}</td>
  <td class="table-body-row-data">
    {% if object.fecha_nacimiento %}
      {{object.fecha_nacimiento|date:"d/m/Y "}}
    {% else %}
      -------
    {% endif %}
  </td>
  <td class="table-body-row-data">{{ object.genero }}</td>

  <td class="table-body-row-data">
    {% if object.telefono %}
      {{object.telefono}}
    {% else %}
      -------
    {% endif %}
  </td>

  <td class="table-body-row-data">
  	{% if object.celular %}
  		{{object.celular}}
  	{% else %}
  		-------
  	{% endif %}
  </td>

  <td class="table-body-row-data">
  	{% if object.email %}
  		{{object.email}}
  	{% else %}
  		-------
  	{% endif %}
  </td>

  <td class="table-body-row-data">
  	{% if object.fecha_registro %}
  		{{object.fecha_registro|date:"d/m/Y h:m:s"}}
  	{% else %}
  		-------
  	{% endif %}
  </td>



  {% if object.activo %}
    <td class="table-body-row-data color-verde-pastel text-center font-weight-bolder icon-circle-check "></td>
  {% else %}
    <td class="table-body-row-data color-red text-center font-weight-bolder icon-circle-cross "></td>
  {% endif%}
</tr>
{%endfor%}

empadronados/templates/empadronado_table_report.html
{% for object in object_list%}
<tr class="table-body-row" id="table_body_row">
  <td class="table-body-row-data"><input type="checkbox" id="ck_{{object.id}}"></td>
  <td class="table-body-row-data">{{ object.id_empadronado }}</td>
  <td class="table-body-row-data"><a href="{% url "empadronado:detail" object.slug %}" class="link color-celeste">{{object.get_nombre_completo}}</a></td>
  <td class="table-body-row-data">{{ object.documento_identificacion }}</td>
  <td class="table-body-row-data">{{ object.numero_documento_identificacion }}</td>
  <td class="table-body-row-data">
    {% if object.fecha_nacimiento %}
      {{object.fecha_nacimiento|date:"d/m/Y "}}
    {% else %}
      -------
    {% endif %}
  </td>
  <td class="table-body-row-data">{{ object.genero }}</td>

  <td class="table-body-row-data">
    {% if object.telefono %}
      {{object.telefono}}
    {% else %}
      -------
    {% endif %}
  </td>

  <td class="table-body-row-data">
  	{% if object.celular %}
  		{{object.celular}}
  	{% else %}
  		-------
  	{% endif %}
  </td>

  <td class="table-body-row-data">
  	{% if object.email %}
  		{{object.email}}
  	{% else %}
  		-------
  	{% endif %}
  </td>

  <td class="table-body-row-data">
  	{% if object.fecha_registro %}
  		{{object.fecha_registro|date:"d/m/Y h:m:s"}}
  	{% else %}
  		-------
  	{% endif %}
  </td>



  {% if object.activo %}
    <td class="table-body-row-data color-verde-pastel text-center font-weight-bolder icon-circle-check "></td>
  {% else %}
    <td class="table-body-row-data color-red text-center font-weight-bolder icon-circle-cross "></td>
  {% endif%}
</tr>
{%endfor%}

empadronados/templates/empadronados.html
{% extends 'base_main_modulo_menu_control.html' %}
{% load static from staticfiles %}
{% block title %}
	Empadronamiento Municipal | Empadronados
{% endblock title %}

{% block src_avatar_modulo %} {% static "imagenes/png/Control_Asistencia_1.png"%} {% endblock src_avatar_modulo %}"
{% block alt_avatar_modulo %} Empadronamiento Municipal {% endblock alt_avatar_modulo %}"

{% block nav-border %}
	border-bottom-red-1
{% endblock nav-border %}

{% block url_menu_control %} {% url "catalogo_modulo_menu_sub_menu:empadronamiento_municipal_menu" %} {% endblock url_menu_control %}

{% block panel_nombre_menu %} Empadronado {% endblock panel_nombre_menu%}

{% block background_agregar_movil %} background-red {% endblock background_agregar_movil %}
{% block background_agregar_desktop %} background-red {% endblock background_agregar_desktop %}

{% block action_form_search_ %} {% url "empadronado:control" %} {% endblock action_form_search_ %}

{% block url_agregar_registro_movil %} {% url "empadronado:create" %} {% endblock url_agregar_registro_movil %}
{% block url_agregar_registro_desktop %} {% url "empadronado:create" %} {% endblock url_agregar_registro_desktop %}

{% block background_table_head %} background-red {% endblock background_table_head %}
{% block background_paginas %} background-red {% endblock background_paginas %}

{% block table_column %}
	<th class="table-head-row-column"><a href="" class="link"><input type="checkbox"> </a></th>
	<th class="table-head-row-column"><a href="" class="link"> Ver </a></th>
	<th class="table-head-row-column"><a href="" class="link"> Código </a></th>
	<th class="table-head-row-column"><a href="" class="link"> Nombre Completo </a></th>
	<th class="table-head-row-column"><a href="" class="link"> Doc. Identificación </a></th>
	<th class="table-head-row-column"><a href="" class="link"> Número Doc. Identificación </a></th>
	<th class="table-head-row-column"><a href="" class="link"> Fecha Nacimiento </a></th>
	<th class="table-head-row-column"><a href="" class="link"> Género </a></th>
	<th class="table-head-row-column"><a href="" class="link"> Télefono </a></th>
	<th class="table-head-row-column"><a href="" class="link"> Celular </a></th>
	<th class="table-head-row-column"><a href="" class="link"> Correo Electrónico </a></th>
	<th class="table-head-row-column"><a href="" class="link"> Fecha Registro </a></th>
	<th class="table-head-row-column"><a href="" class="link"> Activo </a></th>

{% endblock table_column %}

{% block table_row %}
	{% if object_list.count > 0 %}
		{% include "empadronado_table.html" %}
	{% else %}
		{% include "empadronado_table.html" %}
	{% endif %}
{% endblock table_row %}

{% block background_eliminar_movil %} background-red {% endblock background_eliminar_movil %}
{% block background_eliminar_desktop %} background-red {% endblock background_eliminar_desktop %}

{% block background_search_pagina_submit %} background-red {% endblock background_search_pagina_submit %}

{% block script_template %}
	<script id ="input_search_registro_template" type="text/template">
		<input name="search_registro" type="search" id="input_search_registro" class="input-field-default">
	</script>
{% endblock script_template %}